import jhon from "./assets/img/jhon-doe.png";
import jane from "./assets/img/jane-smith.png";
import emily from "./assets/img/emily-jhonson.png";
import michel from "./assets/img/michel-brown.png";
import sarah from "./assets/img/sarah-wilson.png";

export const patients = [
  {
    patient_id: "P001",
    name: "John Doe",
    patient_treatment_status:true,
    patient_img: jhon,
    age: 34,
    gender: "Male",
    phone: "+1234567890",
    email: "johndoe@example.com",
    medical_history: [
      "Tooth sensitivity",
      "Gum disease",
      "Allergic to penicillin",
    ],
    dental_history: [
      {
        treatment: "Gum Disease",
        date: "2023-06-15",
        dentist: "Dr. Smith",
        description: "Inflammation of gum tissue.",
        treatment_status: "Under Observation",
      },
      {
        treatment: "Tooth Decay",
        date: "2023-08-20",
        description: "Breakdown of enamel surface.",
        dentist: "Dr. Clark",
        treatment_status: "Cured",
      },
      {
        treatment: "Cavity",
        date: "2023-08-20",
        dentist: "Dr. Clark",
        description: "Decay causing tooth holes.",
        treatment_status: "Inactive",
      },
    ],
    insurance: {
      provider: "HealthFirst",
      policy_number: "HF1234567890",
    },
    last_dental_visit: "2024-12-10",
    diagnosis: "Cavity in upper right molar",
    treatment_plan: "Filling",
    next_appointment: "2025-01-25",
    notes: "Patient complains of sensitivity to cold.",
    dentist_name: "Dr. Alice Carter",
    current_issue: "Severe tooth pain",
    doctor: "Dr. Smith",
    respiratory_rate:20,
    respiratory_status:'Normal',
    temperature:98.6,
    temperature_status:'Normal',
    heart_rate:78,
    heart_rate_status:'Lower than Average',
  },
  {
    patient_id: "P002",
    name: "Jane Smith",
    patient_treatment_status:true,
    age: 29,
    gender: "Female",
    patient_img: jane,
    phone: "+1234567891",
    email: "janesmith@example.com",
    medical_history: {
      allergies: "None",
      chronic_conditions: "None",
      medications: [],
    },
    dental_history: [
      {
        treatment: "Wisdom Tooth Impaction",
        date: "2024-11-15",
        dentist: "Dr. Michael Green",
        description: "Teeth trapped in gum tissue.",
        treatment_status: "Planned",
      },
      {
        treatment: "Gingivitis",
        date: "2024-12-01",
        dentist: "Dr. Sophia Taylor",
        description: "Inflammation of gums from plaque.",
        treatment_status: "Ongoing",
      },
    ],
    insurance: {
      provider: "DentalCare",
      policy_number: "DC234567890",
    },
    last_dental_visit: "2024-11-15",
    diagnosis: "Wisdom tooth impaction",
    treatment_plan: "Extraction",
    next_appointment: "2025-01-22",
    notes: "Patient reports mild jaw pain.",
    dentist_name: "Dr. Michael Green",
   respiratory_rate: 18,
respiratory_status: 'Slightly Low',
temperature: 99.4,
temperature_status: 'Mildly Elevated',
heart_rate: 90,
heart_rate_status: 'Slightly Elevated',

  },
  {
    patient_id: "P003",
    name: "Emily Johnson",
    patient_treatment_status:false,
    age: 45,
    gender: "Female",
    patient_img: emily,
    phone: "+1234567892",
    email: "emilyjohnson@example.com",
    medical_history: {
      allergies: "Sulfa drugs",
      chronic_conditions: "Hypertension",
      medications: ["Amlodipine"],
    },
    dental_history: [
      {
        treatment: "Periodontitis",
        date: "2024-10-05",
        dentist: "Dr. Lisa White",
        description: "Advanced gum disease damaging tissues.",
        treatment_status: "Ongoing",
      },
      {
        treatment: "Tooth Decay",
        date: "2023-08-20",
        description: "Breakdown of enamel surface.",
        dentist: "Dr. Clark",
        treatment_status: "Cured",
      },
    ],
    insurance: {
      provider: "CarePlus",
      policy_number: "CP87654321",
    },
    last_dental_visit: "2024-10-05",
    diagnosis: "Periodontitis",
    treatment_plan: "Scaling and root planing",
    next_appointment: "2025-01-20",
    notes: "Patient advised on oral hygiene practices.",
    dentist_name: "Dr. Lisa White",
    respiratory_rate: 25,
respiratory_status: 'Elevated',
temperature: 101.2,
temperature_status: 'Fever',
heart_rate: 110,
heart_rate_status: 'Elevated',

  },
  {
    patient_id: "P004",
    name: "Michael Brown",
    patient_treatment_status:true,
    age: 52,
    gender: "Male",
    patient_img: michel,
    phone: "+1234567893",
    email: "michaelbrown@example.com",
    medical_history: {
      allergies: "Latex",
      chronic_conditions: "High cholesterol",
      medications: ["Atorvastatin"],
    },
    dental_history: [
      {
        treatment: "Chipped Tooth",
        date: "2024-09-20",
        dentist: "Dr. David Smith",
        description: "Fractured part of tooth structure.",
        treatment_status: "In Progress",
      },
      {
        treatment: "Cavity",
        date: "2023-08-20",
        dentist: "Dr. Clark",
        description: "Decay causing tooth holes.",
        treatment_status: "Inactive",
      },
    ],
    insurance: {
      provider: "SmileSecure",
      policy_number: "SS345678901",
    },
    last_dental_visit: "2024-09-20",
    diagnosis: "Chipped tooth",
    treatment_plan: "Crown placement",
    next_appointment: "2025-01-23",
    notes: "Patient interested in teeth whitening.",
    dentist_name: "Dr. David Smith",
    respiratory_rate: 16,
respiratory_status: 'Low',
temperature: 96.4,
temperature_status: 'Below Normal',
heart_rate: 72,
heart_rate_status: 'Normal',

  },
  {
    patient_id: "P005",
    name: "Sarah Wilson",
    patient_treatment_status:false,
    age: 37,
    gender: "Female",
    patient_img: sarah,
    phone: "+1234567894",
    email: "sarahwilson@example.com",
    medical_history: {
      allergies: "None",
      chronic_conditions: "Asthma",
      medications: ["Albuterol inhaler"],
    },
    dental_history: [
      {
        treatment: "Gingivitis",
        date: "2024-12-01",
        dentist: "Dr. Sophia Taylor",
        description: "Inflammation of gums from plaque.",
        treatment_status: "Ongoing",
      },
      {
        treatment: "Gum Disease",
        date: "2023-06-15",
        dentist: "Dr. Smith",
        description: "Inflammation of gum tissue.",
        treatment_status: "Under Observation",
      },
    ],
    insurance: {
      provider: "SmileCare",
      policy_number: "SC0987654321",
    },
    last_dental_visit: "2024-12-01",
    diagnosis: "Gingivitis",
    treatment_plan: "Deep cleaning",
    next_appointment: "2025-01-30",
    notes: "Patient requested fluoride treatment.",
    dentist_name: "Dr. Sophia Taylor",
    respiratory_rate: 20,
respiratory_status: 'Normal',
temperature: 98.9,
temperature_status: 'Normal',
heart_rate: 80,
heart_rate_status: 'Average',

  },
  {
    patient_id: "P006",
    name: "David Martinez",
    patient_treatment_status: true,
    age: 40,
    gender: "Male",
    patient_img: jhon, // Reusing John Doe's image
    phone: "+1234567895",
    email: "davidmartinez@example.com",
    medical_history: {
      allergies: "Peanuts",
      chronic_conditions: "Diabetes",
      medications: ["Metformin"],
    },
    dental_history: [
      { treatment: "Root Canal", date: "2024-07-10", dentist: "Dr. Laura Evans", description: "Infected pulp removed from molar.", treatment_status: "Completed" },
      { treatment: "Tooth Extraction", date: "2023-10-25", dentist: "Dr. Ryan Hall", description: "Severely decayed tooth removed.", treatment_status: "Cured" },
    ],
    insurance: { provider: "BrightSmile", policy_number: "BS567890123" },
    last_dental_visit: "2024-07-10",
    diagnosis: "Tooth infection",
    treatment_plan: "Antibiotics and monitoring",
    next_appointment: "2025-02-05",
    notes: "Patient reports mild gum swelling.",
    dentist_name: "Dr. Laura Evans",
    respiratory_rate: 21,
    respiratory_status: "Slightly Elevated",
    temperature: 99.1,
    temperature_status: "Normal",
    heart_rate: 85,
    heart_rate_status: "Slightly Elevated",
  },
  {
    patient_id: "P007",
    name: "Olivia Carter",
    patient_treatment_status: false,
    age: 26,
    gender: "Female",
    patient_img: jane, // Reusing Jane Smith's image
    phone: "+1234567896",
    email: "oliviacarter@example.com",
    medical_history: {
      allergies: "None",
      chronic_conditions: "None",
      medications: [],
    },
    dental_history: [
      { treatment: "Braces", date: "2023-05-12", dentist: "Dr. Steven Harris", description: "Orthodontic treatment for alignment.", treatment_status: "Ongoing" },
      { treatment: "Teeth Whitening", date: "2024-09-15", dentist: "Dr. Lisa Brown", description: "Professional whitening treatment.", treatment_status: "Completed" },
    ],
    insurance: { provider: "PureDental", policy_number: "PD654321098" },
    last_dental_visit: "2024-09-15",
    diagnosis: "Mild misalignment",
    treatment_plan: "Orthodontic follow-up",
    next_appointment: "2025-03-10",
    notes: "Patient satisfied with whitening results.",
    dentist_name: "Dr. Steven Harris",
    respiratory_rate: 18,
    respiratory_status: "Normal",
    temperature: 98.4,
    temperature_status: "Normal",
    heart_rate: 76,
    heart_rate_status: "Normal",
  },
  {
    patient_id: "P008",
    name: "James Anderson",
    patient_treatment_status: true,
    age: 50,
    gender: "Male",
    patient_img: michel, // Reusing Michel Brown's image
    phone: "+1234567897",
    email: "jamesanderson@example.com",
    medical_history: {
      allergies: "Shellfish",
      chronic_conditions: "Hypertension",
      medications: ["Lisinopril"],
    },
    dental_history: [
      { treatment: "Dental Implants", date: "2024-06-30", dentist: "Dr. Rachel Foster", description: "Replacement of missing teeth.", treatment_status: "Ongoing" },
    ],
    insurance: { provider: "HealthSmile", policy_number: "HS876543210" },
    last_dental_visit: "2024-06-30",
    diagnosis: "Multiple missing teeth",
    treatment_plan: "Implant follow-up",
    next_appointment: "2025-02-28",
    notes: "Patient adjusting well to implants.",
    dentist_name: "Dr. Rachel Foster",
    respiratory_rate: 22,
    respiratory_status: "Elevated",
    temperature: 97.8,
    temperature_status: "Normal",
    heart_rate: 88,
    heart_rate_status: "Slightly Elevated",
  },
  {
    patient_id: "P009",
    name: "Sophia Lopez",
    patient_treatment_status: false,
    age: 31,
    gender: "Female",
    patient_img: emily, // Reusing Emily Johnson's image
    phone: "+1234567898",
    email: "sophialopez@example.com",
    medical_history: {
      allergies: "Pollen",
      chronic_conditions: "Migraines",
      medications: ["Sumatriptan"],
    },
    dental_history: [
      { treatment: "Fillings", date: "2024-05-22", dentist: "Dr. Brian Carter", description: "Filling cavities in molars.", treatment_status: "Completed" },
      { treatment: "Gum Recession Treatment", date: "2023-11-10", dentist: "Dr. Amanda Green", description: "Tissue grafting to cover receding gums.", treatment_status: "Ongoing" },
    ],
    insurance: { provider: "SmileGuard", policy_number: "SG123456789" },
    last_dental_visit: "2024-05-22",
    diagnosis: "Mild gum recession",
    treatment_plan: "Regular cleanings and monitoring",
    next_appointment: "2025-03-15",
    notes: "Patient following recommended gum care routine.",
    dentist_name: "Dr. Brian Carter",
    respiratory_rate: 17,
    respiratory_status: "Normal",
    temperature: 98.6,
    temperature_status: "Normal",
    heart_rate: 74,
    heart_rate_status: "Normal",
  },
  {
    patient_id: "P010",
    name: "Ethan Reynolds",
    patient_treatment_status: true,
    age: 55,
    gender: "Male",
    patient_img: sarah, // Reusing Sarah Wilson's image
    phone: "+1234567899",
    email: "ethanreynolds@example.com",
    medical_history: {
      allergies: "None",
      chronic_conditions: "Osteoarthritis",
      medications: ["Ibuprofen"],
    },
    dental_history: [
      { treatment: "Denture Fitting", date: "2024-08-05", dentist: "Dr. Karen Wilson", description: "Fitting of upper and lower dentures.", treatment_status: "In Progress" },
      { treatment: "Deep Cleaning", date: "2023-12-10", dentist: "Dr. John Parker", description: "Removal of plaque and tartar buildup.", treatment_status: "Completed" },
    ],
    insurance: { provider: "DentalShield", policy_number: "DS987654321" },
    last_dental_visit: "2024-08-05",
    diagnosis: "Tooth loss due to aging",
    treatment_plan: "Denture adjustments",
    next_appointment: "2025-02-18",
    notes: "Patient adjusting well to dentures.",
    dentist_name: "Dr. Karen Wilson",
    respiratory_rate: 20,
    respiratory_status: "Normal",
    temperature: 98.5,
    temperature_status: "Normal",
    heart_rate: 79,
    heart_rate_status: "Average",
  },
];
