import jhon from "./assets/img/jhon-doe.png";
import jane from "./assets/img/jane-smith.png";
import emily from "./assets/img/emily-jhonson.png";
import michel from "./assets/img/michel-brown.png";
import sarah from "./assets/img/sarah-wilson.png";

export const patients = 
  [
    {
      patient_id: "P001",
      name: "John Doe",
      patient_img: jhon,
      age: 34,
      gender: "Male",
      phone: "+1234567890",
      email: "johndoe@example.com",
      medical_history: [
        "Tooth sensitivity",
        "Gum disease",
        "Allergic to penicillin",
      ],
      dental_history: [
        {
          treatment: "Gum Disease",
          date: "2023-06-15",
          dentist: "Dr. Smith",
          description: "Inflammation of gum tissue.",
          treatment_status: "Under Observation",
        },
        {
          treatment: "Tooth Decay",
          date: "2023-08-20",
          description: "Breakdown of enamel surface.",
          dentist: "Dr. Clark",
          treatment_status: "Cured",
        },
        {
          treatment: "Cavity",
          date: "2023-08-20",
          dentist: "Dr. Clark",
          description: "Decay causing tooth holes.",
          treatment_status: "Inactive",
        },
      ],
      insurance: {
        provider: "HealthFirst",
        policy_number: "HF1234567890",
      },
      last_dental_visit: "2024-12-10",
      diagnosis: "Cavity in upper right molar",
      treatment_plan: "Filling",
      next_appointment: "2025-01-25",
      notes: "Patient complains of sensitivity to cold.",
      dentist_name: "Dr. Alice Carter",
      current_issue: "Severe tooth pain",
      doctor: "Dr. Smith",
    },
    {
      patient_id: "P002",
      name: "Jane Smith",
      age: 29,
      gender: "Female",
      patient_img: jane,
      phone: "+1234567891",
      email: "janesmith@example.com",
      medical_history: {
        allergies: "None",
        chronic_conditions: "None",
        medications: [],
      },
      dental_history: [
        {
          treatment: "Wisdom Tooth Impaction",
          date: "2024-11-15",
          dentist: "Dr. Michael Green",
          description: "Teeth trapped in gum tissue.",
          treatment_status: "Planned",
        },
        {
          treatment: "Gingivitis",
          date: "2024-12-01",
          dentist: "Dr. Sophia Taylor",
          description: "Inflammation of gums from plaque.",
          treatment_status: "Ongoing",
        },
      ],
      last_dental_visit: "2024-11-15",
      diagnosis: "Wisdom tooth impaction",
      treatment_plan: "Extraction",
      next_appointment: "2025-01-22",
      notes: "Patient reports mild jaw pain.",
      dentist_name: "Dr. Michael Green",
    },
    {
      patient_id: "P003",
      name: "Emily Johnson",
      age: 45,
      gender: "Female",
      patient_img: emily,
      phone: "+1234567892",
      email: "emilyjohnson@example.com",
      medical_history: {
        allergies: "Sulfa drugs",
        chronic_conditions: "Hypertension",
        medications: ["Amlodipine"],
      },
      dental_history: [
        {
          treatment: "Periodontitis",
          date: "2024-10-05",
          dentist: "Dr. Lisa White",
          description: "Advanced gum disease damaging tissues.",
          treatment_status: "Ongoing",
        },  {
          treatment: "Tooth Decay",
          date: "2023-08-20",
          description: "Breakdown of enamel surface.",
          dentist: "Dr. Clark",
          treatment_status: "Cured",
        },
      ],
      last_dental_visit: "2024-10-05",
      diagnosis: "Periodontitis",
      treatment_plan: "Scaling and root planing",
      next_appointment: "2025-01-20",
      notes: "Patient advised on oral hygiene practices.",
      dentist_name: "Dr. Lisa White",
    },
    {
      patient_id: "P004",
      name: "Michael Brown",
      age: 52,
      gender: "Male",
      patient_img: michel,
      phone: "+1234567893",
      email: "michaelbrown@example.com",
      medical_history: {
        allergies: "Latex",
        chronic_conditions: "High cholesterol",
        medications: ["Atorvastatin"],
      },
      dental_history: [
        {
          treatment: "Chipped Tooth",
          date: "2024-09-20",
          dentist: "Dr. David Smith",
          description: "Fractured part of tooth structure.",
          treatment_status: "In Progress",
        },
        {
          treatment: "Cavity",
          date: "2023-08-20",
          dentist: "Dr. Clark",
          description: "Decay causing tooth holes.",
          treatment_status: "Inactive",
        },
      ],
      last_dental_visit: "2024-09-20",
      diagnosis: "Chipped tooth",
      treatment_plan: "Crown placement",
      next_appointment: "2025-01-23",
      notes: "Patient interested in teeth whitening.",
      dentist_name: "Dr. David Smith",
    },
    {
      patient_id: "P005",
      name: "Sarah Wilson",
      age: 37,
      gender: "Female",
      patient_img: sarah,
      phone: "+1234567894",
      email: "sarahwilson@example.com",
      medical_history: {
        allergies: "None",
        chronic_conditions: "Asthma",
        medications: ["Albuterol inhaler"],
      },
      dental_history: [
        {
          treatment: "Gingivitis",
          date: "2024-12-01",
          dentist: "Dr. Sophia Taylor",
          description: "Inflammation of gums from plaque.",
          treatment_status: "Ongoing",
        },
        {
          treatment: "Gum Disease",
          date: "2023-06-15",
          dentist: "Dr. Smith",
          description: "Inflammation of gum tissue.",
          treatment_status: "Under Observation",
        },
      ],
      last_dental_visit: "2024-12-01",
      diagnosis: "Gingivitis",
      treatment_plan: "Deep cleaning",
      next_appointment: "2025-01-30",
      notes: "Patient requested fluoride treatment.",
      dentist_name: "Dr. Sophia Taylor",
    },
  ];
