export const patients = [
  {
    patient_id: "P001",
    name: "Michael Martinez",
    gender: "Male",
    age: 33,
    date_of_birth: "1992-04-12",
    phone: "+1 429-646-7784",
    email: "michael.martinez@example.com",
    address: "788 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Diabetes", "Tooth Sensitivity"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A6362",
      date: "2025-06-19",
      time: "12:30 PM",
      dentist: "Dr. Martinez",
      procedure: "Braces Adjustment",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Cavity detected, needs filling",
    last_visit: {
      date: "2024-09-26",
      procedure: "Root Canal",
      dentist: "Dr. Martinez",
    },
    billing: {
      invoice_id: "INV5251",
      total_amount: 111.5,
      paid_amount: 36.53,
      balance_due: 74.97,
      payment_status: "Partial",
      payment_method: "Debit Card",
    },
    insurance: {
      insurance_provider: "Delta Dental",
      insurance_policy_number: "DD652261737",
      insurance_annual_limit: 2000,
      insurance_used: 543,
      insurance_remaining: 1457,
    },
  },
  {
    patient_id: "P002",
    name: "Richard Martinez",
    gender: "Female",
    age: 46,
    date_of_birth: "1979-03-22",
    phone: "+1 220-895-9542",
    email: "richard.martinez@example.com",
    address: "624 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Gum Disease"],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A1033",
      date: "2025-12-03",
      time: "11:00 AM",
      dentist: "Dr. Lee",
      procedure: "Braces Adjustment",
      status: "Scheduled",
      treatment_status: "Ongoing",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-10-30",
      procedure: "Root Canal",
      dentist: "Dr. Lee",
    },
    billing: {
      invoice_id: "INV9761",
      total_amount: 103.7,
      paid_amount: 67.26,
      balance_due: 36.44,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "MC224917255",
      insurance_annual_limit: 2000,
      insurance_used: 704,
      insurance_remaining: 1296,
    },
  },
  {
    patient_id: "P003",
    name: "Sarah Allen",
    gender: "Female",
    age: 62,
    date_of_birth: "1963-04-14",
    phone: "+1 115-145-5899",
    email: "sarah.allen@example.com",
    address: "466 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: [],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A1026",
      date: "2026-01-27",
      time: "10:30 PM",
      dentist: "Dr. Clark",
      procedure: "Teeth Cleaning",
      status: "Scheduled",
      treatment_status: "Completed",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-03-27",
      procedure: "Cavity Filling",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV6618",
      total_amount: 268.93,
      paid_amount: 64.7,
      balance_due: 204.23,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "BC885449892",
      insurance_annual_limit: 2000,
      insurance_used: 1461,
      insurance_remaining: 539,
    },
  },
  {
    patient_id: "P004",
    name: "David Anderson",
    gender: "Female",
    age: 43,
    date_of_birth: "1982-12-06",
    phone: "+1 708-270-3776",
    email: "david.anderson@example.com",
    address: "604 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: [],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A3270",
      date: "2026-01-25",
      time: "8:30 PM",
      dentist: "Dr. Brown",
      procedure: "Braces Adjustment",
      status: "Scheduled",
      treatment_status: "Scheduled",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-08-04",
      procedure: "Extraction",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV6043",
      total_amount: 236.24,
      paid_amount: 55.42,
      balance_due: 180.82,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "Delta Dental",
      insurance_policy_number: "DD509164007",
      insurance_annual_limit: 2000,
      insurance_used: 464,
      insurance_remaining: 1536,
    },
  },
  {
    patient_id: "P005",
    name: "Susan Hall",
    gender: "Female",
    age: 38,
    date_of_birth: "1987-02-18",
    phone: "+1 505-167-1098",
    email: "susan.hall@example.com",
    address: "967 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: [],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A6470",
      date: "2026-02-13",
      time: "8:00 AM",
      dentist: "Dr. Emily Carter",
      procedure: "Cavity Filling",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Cavity detected, needs filling",
    last_visit: {
      date: "2024-03-31",
      procedure: "Cavity Filling",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV6717",
      total_amount: 211.01,
      paid_amount: 81.32,
      balance_due: 129.69,
      payment_status: "Partial",
      payment_method: "Credit Card",
    },
    insurance: {
      insurance_provider: "Delta Dental",
      insurance_policy_number: "CG229713030",
      insurance_annual_limit: 2000,
      insurance_used: 1312,
      insurance_remaining: 688,
    },
  },
  {
    patient_id: "P006",
    name: "Maria Lewis",
    gender: "Female",
    age: 64,
    date_of_birth: "1961-01-01",
    phone: "+1 975-181-2103",
    email: "maria.lewis@example.com",
    address: "615 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Pollen"],
      previous_conditions: ["Gingivitis"],
      current_medications: ["None"],
    },
    appointments: {
      appointment_id: "A8209",
      date: "2025-05-13",
      time: "9:30 AM",
      dentist: "Dr. Brown",
      procedure: "Cavity Filling",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Cavity detected, needs filling",
    last_visit: {
      date: "2024-12-05",
      procedure: "Cavity Filling",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV9102",
      total_amount: 231.76,
      paid_amount: 136.37,
      balance_due: 95.39,
      payment_status: "Partial",
      payment_method: "Credit Card",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "HF824903629",
      insurance_annual_limit: 2000,
      insurance_used: 712,
      insurance_remaining: 1288,
    },
  },
  {
    patient_id: "P007",
    name: "Jane King",
    gender: "Female",
    age: 37,
    date_of_birth: "1988-02-11",
    phone: "+1 236-679-1496",
    email: "jane.king@example.com",
    address: "796 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["None"],
      previous_conditions: ["Tooth Sensitivity", "Gum Disease"],
      current_medications: ["None"],
    },
    appointments: {
      appointment_id: "A2124",
      date: "2025-06-09",
      time: "10:00 AM",
      dentist: "Dr. Brown",
      procedure: "Braces Adjustment",
      status: "Completed",
      treatment_status: "Ongoing",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-03-20",
      procedure: "Extraction",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV8157",
      total_amount: 227.15,
      paid_amount: 108.89,
      balance_due: 118.26,
      payment_status: "Partial",
      payment_method: "Debit Card",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "HF497710233",
      insurance_annual_limit: 2000,
      insurance_used: 901,
      insurance_remaining: 1099,
    },
  },
  {
    patient_id: "P008",
    name: "John Anderson",
    gender: "Male",
    age: 49,
    date_of_birth: "1976-06-03",
    phone: "+1 110-963-6092",
    email: "john.anderson@example.com",
    address: "637 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: [],
      current_medications: ["Paracetamol"],
    },
    appointments: {
      appointment_id: "A8958",
      date: "2025-09-08",
      time: "12:00 PM",
      dentist: "Dr. Lee",
      procedure: "Cavity Filling",
      status: "Cancelled",
      treatment_status: "Completed",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-08-05",
      procedure: "Braces Adjustment",
      dentist: "Dr. Lee",
    },
    billing: {
      invoice_id: "INV9924",
      total_amount: 213.03,
      paid_amount: 30.07,
      balance_due: 182.96,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "HF772303030",
      insurance_annual_limit: 2000,
      insurance_used: 62,
      insurance_remaining: 1938,
    },
  },
  {
    patient_id: "P009",
    name: "Barbara Allen",
    gender: "Female",
    age: 55,
    date_of_birth: "1970-01-18",
    phone: "+1 460-611-9583",
    email: "barbara.allen@example.com",
    address: "878 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Pollen"],
      previous_conditions: ["Gingivitis"],
      current_medications: ["None"],
    },
    appointments: {
      appointment_id: "A7602",
      date: "2025-08-21",
      time: "12:30 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Root Canal",
      status: "Completed",
      treatment_status: "Ongoing",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-03-22",
      procedure: "Braces Adjustment",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV6353",
      total_amount: 295.58,
      paid_amount: 104.27,
      balance_due: 191.31,
      payment_status: "Partial",
      payment_method: "Debit Card",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "DD121618231",
      insurance_annual_limit: 2000,
      insurance_used: 1087,
      insurance_remaining: 913,
    },
  },
  {
    patient_id: "P010",
    name: "Michael Wright",
    gender: "Male",
    age: 19,
    date_of_birth: "2006-10-20",
    phone: "+1 164-945-5484",
    email: "michael.wright@example.com",
    address: "443 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Gum Disease", "Hypertension"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A1093",
      date: "2025-03-07",
      time: "10:30 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Teeth Cleaning",
      status: "Completed",
      treatment_status: "Ongoing",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-03-29",
      procedure: "Root Canal",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV5561",
      total_amount: 286.35,
      paid_amount: 272.92,
      balance_due: 13.43,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "HF846024446",
      insurance_annual_limit: 2000,
      insurance_used: 79,
      insurance_remaining: 1921,
    },
  },
  {
    patient_id: "P011",
    name: "Charles Anderson",
    gender: "Male",
    age: 21,
    date_of_birth: "2004-05-22",
    phone: "+1 115-725-3068",
    email: "charles.anderson@example.com",
    address: "372 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Penicillin"],
      previous_conditions: ["Tooth Sensitivity", "Diabetes"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A4921",
      date: "2026-02-16",
      time: "12:30 PM",
      dentist: "Dr. Brown",
      procedure: "Extraction",
      status: "Cancelled",
      treatment_status: "Completed",
    },
    note: "Gum inflammation, prescribe rinse",
    last_visit: {
      date: "2024-04-01",
      procedure: "Root Canal",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV5756",
      total_amount: 135.64,
      paid_amount: 1.98,
      balance_due: 133.66,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "HF728158318",
      insurance_annual_limit: 2000,
      insurance_used: 1409,
      insurance_remaining: 591,
    },
  },
  {
    patient_id: "P012",
    name: "Maria King",
    gender: "Male",
    age: 41,
    date_of_birth: "1984-11-05",
    phone: "+1 993-310-4795",
    email: "maria.king@example.com",
    address: "307 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: [],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A1712",
      date: "2025-11-15",
      time: "8:00 AM",
      dentist: "Dr. Martinez",
      procedure: "Root Canal",
      status: "Scheduled",
      treatment_status: "Completed",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-10-14",
      procedure: "Cavity Filling",
      dentist: "Dr. Martinez",
    },
    billing: {
      invoice_id: "INV6927",
      total_amount: 158.9,
      paid_amount: 13.13,
      balance_due: 145.77,
      payment_status: "Partial",
      payment_method: "Debit Card",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "DD409321097",
      insurance_annual_limit: 2000,
      insurance_used: 1008,
      insurance_remaining: 992,
    },
  },
  {
    patient_id: "P013",
    name: "Patricia Doe",
    gender: "Male",
    age: 25,
    date_of_birth: "2000-04-03",
    phone: "+1 538-449-4947",
    email: "patricia.doe@example.com",
    address: "243 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Gingivitis"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A8300",
      date: "2025-07-17",
      time: "12:30 PM",
      dentist: "Dr. Lee",
      procedure: "Cavity Filling",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Tooth sensitivity, monitor diet",
    last_visit: {
      date: "2024-05-24",
      procedure: "Cavity Filling",
      dentist: "Dr. Lee",
    },
    billing: {
      invoice_id: "INV9484",
      total_amount: 79.42,
      paid_amount: 8.22,
      balance_due: 71.2,
      payment_status: "Partial",
      payment_method: "Debit Card",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "CG267744610",
      insurance_annual_limit: 2000,
      insurance_used: 141,
      insurance_remaining: 1859,
    },
  },
  {
    patient_id: "P014",
    name: "Maria Clark",
    gender: "Female",
    age: 28,
    date_of_birth: "1997-08-24",
    phone: "+1 720-153-5153",
    email: "maria.clark@example.com",
    address: "995 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: [],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A4017",
      date: "2025-08-21",
      time: "8:00 PM",
      dentist: "Dr. Clark",
      procedure: "Cavity Filling",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-10-04",
      procedure: "Cavity Filling",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV9750",
      total_amount: 288.36,
      paid_amount: 128.1,
      balance_due: 160.26,
      payment_status: "Partial",
      payment_method: "Credit Card",
    },
    insurance: {
      insurance_provider: "MediCare",
      insurance_policy_number: "HF515894964",
      insurance_annual_limit: 2000,
      insurance_used: 427,
      insurance_remaining: 1573,
    },
  },
  {
    patient_id: "P015",
    name: "Jane Clark",
    gender: "Male",
    age: 66,
    date_of_birth: "1959-07-20",
    phone: "+1 825-478-4633",
    email: "jane.clark@example.com",
    address: "649 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Hypertension"],
      current_medications: ["Ibuprofen"],
    },
    appointments: {
      appointment_id: "A6911",
      date: "2025-09-15",
      time: "9:30 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Teeth Cleaning",
      status: "Completed",
      treatment_status: "Ongoing",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-11-06",
      procedure: "Braces Adjustment",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV6351",
      total_amount: 277.23,
      paid_amount: 13.47,
      balance_due: 263.76,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "MC808804470",
      insurance_annual_limit: 2000,
      insurance_used: 1411,
      insurance_remaining: 589,
    },
  },
  {
    patient_id: "P016",
    name: "Emily Walker",
    gender: "Female",
    age: 23,
    date_of_birth: "2002-12-01",
    phone: "+1 659-206-7508",
    email: "emily.walker@example.com",
    address: "101 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Penicillin"],
      previous_conditions: ["Gingivitis", "Hypertension"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A6396",
      date: "2025-08-09",
      time: "9:00 PM",
      dentist: "Dr. Clark",
      procedure: "Teeth Cleaning",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Cavity detected, needs filling",
    last_visit: {
      date: "2024-06-29",
      procedure: "Cavity Filling",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV9523",
      total_amount: 242.57,
      paid_amount: 25.63,
      balance_due: 216.94,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "DD768129860",
      insurance_annual_limit: 2000,
      insurance_used: 390,
      insurance_remaining: 1610,
    },
  },
  {
    patient_id: "P017",
    name: "Linda King",
    gender: "Male",
    age: 49,
    date_of_birth: "1976-06-28",
    phone: "+1 274-447-3040",
    email: "linda.king@example.com",
    address: "455 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Pollen"],
      previous_conditions: [],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A8508",
      date: "2026-01-15",
      time: "11:00 AM",
      dentist: "Dr. Clark",
      procedure: "Cavity Filling",
      status: "Scheduled",
      treatment_status: "Completed",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-05-01",
      procedure: "Extraction",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV6019",
      total_amount: 65.65,
      paid_amount: 52.61,
      balance_due: 13.04,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "DD639351811",
      insurance_annual_limit: 2000,
      insurance_used: 380,
      insurance_remaining: 1620,
    },
  },
  {
    patient_id: "P018",
    name: "Barbara King",
    gender: "Male",
    age: 66,
    date_of_birth: "1959-08-13",
    phone: "+1 727-718-6828",
    email: "barbara.king@example.com",
    address: "720 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Pollen"],
      previous_conditions: ["Gum Disease"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A9295",
      date: "2025-11-26",
      time: "12:30 AM",
      dentist: "Dr. Brown",
      procedure: "Extraction",
      status: "Scheduled",
      treatment_status: "Completed",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-11-03",
      procedure: "Teeth Cleaning",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV6917",
      total_amount: 228.19,
      paid_amount: 129.5,
      balance_due: 98.69,
      payment_status: "Partial",
      payment_method: "Credit Card",
    },
    insurance: {
      insurance_provider: "MediCare",
      insurance_policy_number: "MC413441540",
      insurance_annual_limit: 2000,
      insurance_used: 462,
      insurance_remaining: 1538,
    },
  },
  {
    patient_id: "P019",
    name: "Sarah Doe",
    gender: "Female",
    age: 31,
    date_of_birth: "1994-02-28",
    phone: "+1 388-869-5420",
    email: "sarah.doe@example.com",
    address: "551 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Gum Disease", "Tooth Sensitivity"],
      current_medications: ["Ibuprofen"],
    },
    appointments: {
      appointment_id: "A4880",
      date: "2025-09-13",
      time: "9:30 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Teeth Cleaning",
      status: "Cancelled",
      treatment_status: "Ongoing",
    },
    note: "Cavity detected, needs filling",
    last_visit: {
      date: "2024-02-26",
      procedure: "Braces Adjustment",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV9914",
      total_amount: 125.78,
      paid_amount: 49.88,
      balance_due: 75.9,
      payment_status: "Partial",
      payment_method: "Credit Card",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "CG519458764",
      insurance_annual_limit: 2000,
      insurance_used: 606,
      insurance_remaining: 1394,
    },
  },
  {
    patient_id: "P020",
    name: "John Harris",
    gender: "Female",
    age: 58,
    date_of_birth: "1967-04-15",
    phone: "+1 407-956-3585",
    email: "john.harris@example.com",
    address: "182 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Gingivitis"],
      current_medications: ["Paracetamol"],
    },
    appointments: {
      appointment_id: "A3122",
      date: "2025-09-13",
      time: "11:30 PM",
      dentist: "Dr. Clark",
      procedure: "Braces Adjustment",
      status: "Cancelled",
      treatment_status: "Completed",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-12-06",
      procedure: "Teeth Cleaning",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV5661",
      total_amount: 112.05,
      paid_amount: 105.75,
      balance_due: 6.3,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "MediCare",
      insurance_policy_number: "CG637346246",
      insurance_annual_limit: 2000,
      insurance_used: 1371,
      insurance_remaining: 629,
    },
  },
  {
    patient_id: "P021",
    name: "Richard Martinez",
    gender: "Male",
    age: 69,
    date_of_birth: "1956-08-14",
    phone: "+1 851-325-1900",
    email: "richard.martinez@example.com",
    address: "542 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Hypertension"],
      current_medications: ["None"],
    },
    appointments: {
      appointment_id: "A2219",
      date: "2025-06-10",
      time: "11:00 AM",
      dentist: "Dr. Clark",
      procedure: "Cavity Filling",
      status: "Completed",
      treatment_status: "Ongoing",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-03-13",
      procedure: "Root Canal",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV8715",
      total_amount: 250.72,
      paid_amount: 99.02,
      balance_due: 151.7,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "CG233870037",
      insurance_annual_limit: 2000,
      insurance_used: 1014,
      insurance_remaining: 986,
    },
  },
  {
    patient_id: "P022",
    name: "Joseph Johnson",
    gender: "Female",
    age: 42,
    date_of_birth: "1983-12-20",
    phone: "+1 816-410-6805",
    email: "joseph.johnson@example.com",
    address: "748 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: [],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A4257",
      date: "2025-04-04",
      time: "12:30 AM",
      dentist: "Dr. Emily Carter",
      procedure: "Cavity Filling",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-09-14",
      procedure: "Braces Adjustment",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV7619",
      total_amount: 298.3,
      paid_amount: 120.87,
      balance_due: 177.43,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "MC693255882",
      insurance_annual_limit: 2000,
      insurance_used: 1317,
      insurance_remaining: 683,
    },
  },
  {
    patient_id: "P023",
    name: "Jennifer Taylor",
    gender: "Female",
    age: 33,
    date_of_birth: "1992-08-21",
    phone: "+1 850-331-1481",
    email: "jennifer.taylor@example.com",
    address: "432 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Diabetes"],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A1393",
      date: "2025-07-31",
      time: "11:00 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Braces Adjustment",
      status: "Completed",
      treatment_status: "Scheduled",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-04-29",
      procedure: "Root Canal",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV6679",
      total_amount: 270.17,
      paid_amount: 119.23,
      balance_due: 150.94,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "MC213862420",
      insurance_annual_limit: 2000,
      insurance_used: 1411,
      insurance_remaining: 589,
    },
  },
  {
    patient_id: "P024",
    name: "Richard Johnson",
    gender: "Female",
    age: 30,
    date_of_birth: "1995-08-09",
    phone: "+1 786-318-7556",
    email: "richard.johnson@example.com",
    address: "782 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Hypertension"],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A6940",
      date: "2025-10-12",
      time: "8:30 AM",
      dentist: "Dr. Brown",
      procedure: "Braces Adjustment",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-04-13",
      procedure: "Teeth Cleaning",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV7494",
      total_amount: 212.88,
      paid_amount: 103.89,
      balance_due: 108.99,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "MediCare",
      insurance_policy_number: "CG156959066",
      insurance_annual_limit: 2000,
      insurance_used: 1379,
      insurance_remaining: 621,
    },
  },
  {
    patient_id: "P025",
    name: "Jennifer Martinez",
    gender: "Female",
    age: 39,
    date_of_birth: "1986-12-06",
    phone: "+1 112-949-4828",
    email: "jennifer.martinez@example.com",
    address: "538 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Tooth Sensitivity"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A5114",
      date: "2025-09-27",
      time: "12:00 AM",
      dentist: "Dr. Emily Carter",
      procedure: "Root Canal",
      status: "Scheduled",
      treatment_status: "Scheduled",
    },
    note: "Gum inflammation, prescribe rinse",
    last_visit: {
      date: "2024-12-18",
      procedure: "Teeth Cleaning",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV7046",
      total_amount: 297.89,
      paid_amount: 259.11,
      balance_due: 38.78,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "BC996396465",
      insurance_annual_limit: 2000,
      insurance_used: 698,
      insurance_remaining: 1302,
    },
  },
  {
    patient_id: "P026",
    name: "Elizabeth Taylor",
    gender: "Female",
    age: 61,
    date_of_birth: "1964-02-20",
    phone: "+1 567-236-6219",
    email: "elizabeth.taylor@example.com",
    address: "182 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["None"],
      previous_conditions: [],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A6777",
      date: "2025-04-20",
      time: "10:00 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Root Canal",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-04-11",
      procedure: "Braces Adjustment",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV6271",
      total_amount: 162.69,
      paid_amount: 46.85,
      balance_due: 115.84,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "Delta Dental",
      insurance_policy_number: "BC699750354",
      insurance_annual_limit: 2000,
      insurance_used: 67,
      insurance_remaining: 1933,
    },
  },
  {
    patient_id: "P027",
    name: "Jane Brown",
    gender: "Male",
    age: 23,
    date_of_birth: "2002-12-14",
    phone: "+1 200-692-5464",
    email: "jane.brown@example.com",
    address: "616 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["None"],
      previous_conditions: [],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A3043",
      date: "2025-06-02",
      time: "12:30 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Cavity Filling",
      status: "Cancelled",
      treatment_status: "Ongoing",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-12-07",
      procedure: "Extraction",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV9359",
      total_amount: 157.66,
      paid_amount: 46.98,
      balance_due: 110.68,
      payment_status: "Partial",
      payment_method: "Debit Card",
    },
    insurance: {
      insurance_provider: "MediCare",
      insurance_policy_number: "MC305829691",
      insurance_annual_limit: 2000,
      insurance_used: 432,
      insurance_remaining: 1568,
    },
  },
  {
    patient_id: "P028",
    name: "Elizabeth Scott",
    gender: "Male",
    age: 57,
    date_of_birth: "1968-06-28",
    phone: "+1 374-288-5105",
    email: "elizabeth.scott@example.com",
    address: "563 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Tooth Sensitivity", "Gingivitis"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A2184",
      date: "2025-02-18",
      time: "9:30 AM",
      dentist: "Dr. Brown",
      procedure: "Extraction",
      status: "Scheduled",
      treatment_status: "Ongoing",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-03-06",
      procedure: "Braces Adjustment",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV5572",
      total_amount: 221.14,
      paid_amount: 219.44,
      balance_due: 1.7,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "HF733012131",
      insurance_annual_limit: 2000,
      insurance_used: 1315,
      insurance_remaining: 685,
    },
  },
  {
    patient_id: "P029",
    name: "Jane Davis",
    gender: "Male",
    age: 39,
    date_of_birth: "1986-08-19",
    phone: "+1 691-331-8039",
    email: "jane.davis@example.com",
    address: "863 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Hypertension", "Diabetes"],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A1945",
      date: "2025-05-04",
      time: "11:00 AM",
      dentist: "Dr. Brown",
      procedure: "Teeth Cleaning",
      status: "Completed",
      treatment_status: "Ongoing",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-05-11",
      procedure: "Root Canal",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV7246",
      total_amount: 183.75,
      paid_amount: 99.32,
      balance_due: 84.43,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "MediCare",
      insurance_policy_number: "HF377521677",
      insurance_annual_limit: 2000,
      insurance_used: 5,
      insurance_remaining: 1995,
    },
  },
  {
    patient_id: "P030",
    name: "David King",
    gender: "Female",
    age: 20,
    date_of_birth: "2005-05-26",
    phone: "+1 892-554-8259",
    email: "david.king@example.com",
    address: "336 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Gum Disease"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A9749",
      date: "2025-07-03",
      time: "12:30 PM",
      dentist: "Dr. Brown",
      procedure: "Cavity Filling",
      status: "Scheduled",
      treatment_status: "Completed",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-04-22",
      procedure: "Teeth Cleaning",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV6987",
      total_amount: 155.72,
      paid_amount: 125.23,
      balance_due: 30.49,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Delta Dental",
      insurance_policy_number: "DD204000251",
      insurance_annual_limit: 2000,
      insurance_used: 483,
      insurance_remaining: 1517,
    },
  },
  {
    patient_id: "P031",
    name: "Elizabeth Martinez",
    gender: "Male",
    age: 35,
    date_of_birth: "1990-05-08",
    phone: "+1 860-551-4610",
    email: "elizabeth.martinez@example.com",
    address: "314 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Gum Disease", "Tooth Sensitivity"],
      current_medications: ["Ibuprofen"],
    },
    appointments: {
      appointment_id: "A2518",
      date: "2025-04-21",
      time: "11:00 PM",
      dentist: "Dr. Brown",
      procedure: "Extraction",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-02-18",
      procedure: "Extraction",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV8151",
      total_amount: 199.55,
      paid_amount: 66.3,
      balance_due: 133.25,
      payment_status: "Partial",
      payment_method: "Credit Card",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "BC300111066",
      insurance_annual_limit: 2000,
      insurance_used: 454,
      insurance_remaining: 1546,
    },
  },
  {
    patient_id: "P032",
    name: "Elizabeth Doe",
    gender: "Male",
    age: 56,
    date_of_birth: "1969-09-18",
    phone: "+1 309-135-7962",
    email: "elizabeth.doe@example.com",
    address: "200 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Diabetes"],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A4703",
      date: "2025-09-30",
      time: "11:30 PM",
      dentist: "Dr. Clark",
      procedure: "Braces Adjustment",
      status: "Scheduled",
      treatment_status: "Scheduled",
    },
    note: "Gum inflammation, prescribe rinse",
    last_visit: {
      date: "2024-08-27",
      procedure: "Root Canal",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV9842",
      total_amount: 127.17,
      paid_amount: 32.73,
      balance_due: 94.44,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "HF432770739",
      insurance_annual_limit: 2000,
      insurance_used: 1058,
      insurance_remaining: 942,
    },
  },
  {
    patient_id: "P033",
    name: "Maria Martinez",
    gender: "Male",
    age: 56,
    date_of_birth: "1969-02-04",
    phone: "+1 525-168-4459",
    email: "maria.martinez@example.com",
    address: "611 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["None"],
      previous_conditions: ["Gum Disease"],
      current_medications: ["None"],
    },
    appointments: {
      appointment_id: "A3842",
      date: "2025-11-18",
      time: "10:00 AM",
      dentist: "Dr. Lee",
      procedure: "Teeth Cleaning",
      status: "Cancelled",
      treatment_status: "Ongoing",
    },
    note: "Gum inflammation, prescribe rinse",
    last_visit: {
      date: "2024-08-03",
      procedure: "Root Canal",
      dentist: "Dr. Lee",
    },
    billing: {
      invoice_id: "INV9950",
      total_amount: 109.37,
      paid_amount: 85.69,
      balance_due: 23.68,
      payment_status: "Partial",
      payment_method: "Credit Card",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "HF894666481",
      insurance_annual_limit: 2000,
      insurance_used: 1370,
      insurance_remaining: 630,
    },
  },
  {
    patient_id: "P034",
    name: "Jennifer Allen",
    gender: "Male",
    age: 51,
    date_of_birth: "1974-12-18",
    phone: "+1 510-260-7774",
    email: "jennifer.allen@example.com",
    address: "129 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["None"],
      previous_conditions: [],
      current_medications: ["Paracetamol"],
    },
    appointments: {
      appointment_id: "A9962",
      date: "2025-02-18",
      time: "11:30 AM",
      dentist: "Dr. Clark",
      procedure: "Cavity Filling",
      status: "Scheduled",
      treatment_status: "Scheduled",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-06-22",
      procedure: "Teeth Cleaning",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV6110",
      total_amount: 58.16,
      paid_amount: 27.43,
      balance_due: 30.73,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "CG722178059",
      insurance_annual_limit: 2000,
      insurance_used: 1109,
      insurance_remaining: 891,
    },
  },
  {
    patient_id: "P035",
    name: "James Scott",
    gender: "Female",
    age: 60,
    date_of_birth: "1965-02-27",
    phone: "+1 998-593-4334",
    email: "james.scott@example.com",
    address: "516 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Hypertension"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A1962",
      date: "2025-10-27",
      time: "11:30 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Teeth Cleaning",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-08-03",
      procedure: "Extraction",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV8438",
      total_amount: 233.09,
      paid_amount: 108.3,
      balance_due: 124.79,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "CG419852189",
      insurance_annual_limit: 2000,
      insurance_used: 789,
      insurance_remaining: 1211,
    },
  },
  {
    patient_id: "P036",
    name: "Sarah Young",
    gender: "Male",
    age: 38,
    date_of_birth: "1987-08-07",
    phone: "+1 609-306-7228",
    email: "sarah.young@example.com",
    address: "494 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Pollen"],
      previous_conditions: ["Tooth Sensitivity", "Hypertension"],
      current_medications: ["Ibuprofen"],
    },
    appointments: {
      appointment_id: "A6081",
      date: "2025-05-24",
      time: "8:00 AM",
      dentist: "Dr. Clark",
      procedure: "Cavity Filling",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Tooth sensitivity, monitor diet",
    last_visit: {
      date: "2024-11-05",
      procedure: "Teeth Cleaning",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV6390",
      total_amount: 200.44,
      paid_amount: 90.64,
      balance_due: 109.8,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Delta Dental",
      insurance_policy_number: "CG856275081",
      insurance_annual_limit: 2000,
      insurance_used: 195,
      insurance_remaining: 1805,
    },
  },
  {
    patient_id: "P037",
    name: "Maria Hall",
    gender: "Male",
    age: 30,
    date_of_birth: "1995-08-25",
    phone: "+1 290-832-2764",
    email: "maria.hall@example.com",
    address: "380 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Hypertension"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A8506",
      date: "2025-09-21",
      time: "9:30 PM",
      dentist: "Dr. Brown",
      procedure: "Root Canal",
      status: "Scheduled",
      treatment_status: "Scheduled",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-04-21",
      procedure: "Root Canal",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV7800",
      total_amount: 74.32,
      paid_amount: 48.86,
      balance_due: 25.46,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "MediCare",
      insurance_policy_number: "CG257679953",
      insurance_annual_limit: 2000,
      insurance_used: 19,
      insurance_remaining: 1981,
    },
  },
  {
    patient_id: "P038",
    name: "Joseph Brown",
    gender: "Female",
    age: 62,
    date_of_birth: "1963-11-01",
    phone: "+1 431-688-9213",
    email: "joseph.brown@example.com",
    address: "932 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["None"],
      previous_conditions: [],
      current_medications: ["None"],
    },
    appointments: {
      appointment_id: "A9583",
      date: "2025-03-16",
      time: "8:00 AM",
      dentist: "Dr. Martinez",
      procedure: "Root Canal",
      status: "Scheduled",
      treatment_status: "Completed",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-09-25",
      procedure: "Teeth Cleaning",
      dentist: "Dr. Martinez",
    },
    billing: {
      invoice_id: "INV8866",
      total_amount: 240.73,
      paid_amount: 110.23,
      balance_due: 130.5,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "MC318065118",
      insurance_annual_limit: 2000,
      insurance_used: 687,
      insurance_remaining: 1313,
    },
  },
  {
    patient_id: "P039",
    name: "Richard Anderson",
    gender: "Female",
    age: 21,
    date_of_birth: "2004-04-19",
    phone: "+1 560-116-8268",
    email: "richard.anderson@example.com",
    address: "881 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: [],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A1389",
      date: "2026-01-21",
      time: "8:00 PM",
      dentist: "Dr. Lee",
      procedure: "Braces Adjustment",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Cavity detected, needs filling",
    last_visit: {
      date: "2024-08-25",
      procedure: "Cavity Filling",
      dentist: "Dr. Lee",
    },
    billing: {
      invoice_id: "INV5608",
      total_amount: 131.85,
      paid_amount: 64.79,
      balance_due: 67.06,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "BC378099146",
      insurance_annual_limit: 2000,
      insurance_used: 500,
      insurance_remaining: 1500,
    },
  },
  {
    patient_id: "P040",
    name: "John Wright",
    gender: "Female",
    age: 35,
    date_of_birth: "1990-11-14",
    phone: "+1 872-285-6084",
    email: "john.wright@example.com",
    address: "382 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Tooth Sensitivity"],
      current_medications: ["Paracetamol"],
    },
    appointments: {
      appointment_id: "A1081",
      date: "2026-01-06",
      time: "11:30 PM",
      dentist: "Dr. Clark",
      procedure: "Braces Adjustment",
      status: "Scheduled",
      treatment_status: "Scheduled",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2025-01-08",
      procedure: "Extraction",
      dentist: "Dr. Clark",
    },
    billing: {
      invoice_id: "INV9270",
      total_amount: 179.64,
      paid_amount: 120.34,
      balance_due: 59.3,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Delta Dental",
      insurance_policy_number: "DD723033883",
      insurance_annual_limit: 2000,
      insurance_used: 1303,
      insurance_remaining: 697,
    },
  },
  {
    patient_id: "P041",
    name: "Elizabeth Anderson",
    gender: "Female",
    age: 26,
    date_of_birth: "1999-02-25",
    phone: "+1 949-369-2806",
    email: "elizabeth.anderson@example.com",
    address: "676 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: [],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A5584",
      date: "2026-02-03",
      time: "12:30 PM",
      dentist: "Dr. Brown",
      procedure: "Teeth Cleaning",
      status: "Cancelled",
      treatment_status: "Ongoing",
    },
    note: "Gum inflammation, prescribe rinse",
    last_visit: {
      date: "2024-10-16",
      procedure: "Cavity Filling",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV5003",
      total_amount: 196.24,
      paid_amount: 162.87,
      balance_due: 33.37,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "MediCare",
      insurance_policy_number: "MC171422761",
      insurance_annual_limit: 2000,
      insurance_used: 1443,
      insurance_remaining: 557,
    },
  },
  {
    patient_id: "P042",
    name: "Emily Martinez",
    gender: "Male",
    age: 48,
    date_of_birth: "1977-04-12",
    phone: "+1 103-609-4345",
    email: "emily.martinez@example.com",
    address: "249 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["None"],
      previous_conditions: ["Diabetes"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A9926",
      date: "2025-03-28",
      time: "8:00 PM",
      dentist: "Dr. Martinez",
      procedure: "Extraction",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Cavity detected, needs filling",
    last_visit: {
      date: "2024-12-04",
      procedure: "Root Canal",
      dentist: "Dr. Martinez",
    },
    billing: {
      invoice_id: "INV5029",
      total_amount: 78.44,
      paid_amount: 16.17,
      balance_due: 62.27,
      payment_status: "Partial",
      payment_method: "Debit Card",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "CG157123537",
      insurance_annual_limit: 2000,
      insurance_used: 1411,
      insurance_remaining: 589,
    },
  },
  {
    patient_id: "P043",
    name: "Thomas Brown",
    gender: "Male",
    age: 39,
    date_of_birth: "1986-04-15",
    phone: "+1 875-349-3847",
    email: "thomas.brown@example.com",
    address: "617 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Hypertension", "Gingivitis"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A2737",
      date: "2025-08-12",
      time: "9:00 AM",
      dentist: "Dr. Lee",
      procedure: "Braces Adjustment",
      status: "Completed",
      treatment_status: "Completed",
    },
    note: "Cavity detected, needs filling",
    last_visit: {
      date: "2024-06-14",
      procedure: "Root Canal",
      dentist: "Dr. Lee",
    },
    billing: {
      invoice_id: "INV9262",
      total_amount: 194.39,
      paid_amount: 156.85,
      balance_due: 37.54,
      payment_status: "Partial",
      payment_method: "Debit Card",
    },
    insurance: {
      insurance_provider: "Delta Dental",
      insurance_policy_number: "DD592010480",
      insurance_annual_limit: 2000,
      insurance_used: 1064,
      insurance_remaining: 936,
    },
  },
  {
    patient_id: "P044",
    name: "Robert Smith",
    gender: "Male",
    age: 52,
    date_of_birth: "1973-06-15",
    phone: "+1 911-263-8268",
    email: "robert.smith@example.com",
    address: "749 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Tooth Sensitivity"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A2914",
      date: "2025-06-16",
      time: "12:30 PM",
      dentist: "Dr. Lee",
      procedure: "Cavity Filling",
      status: "Scheduled",
      treatment_status: "Completed",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-03-09",
      procedure: "Cavity Filling",
      dentist: "Dr. Lee",
    },
    billing: {
      invoice_id: "INV5730",
      total_amount: 226.03,
      paid_amount: 217.61,
      balance_due: 8.42,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "CG610550781",
      insurance_annual_limit: 2000,
      insurance_used: 164,
      insurance_remaining: 1836,
    },
  },
  {
    patient_id: "P045",
    name: "Robert Taylor",
    gender: "Female",
    age: 54,
    date_of_birth: "1971-12-06",
    phone: "+1 248-559-1481",
    email: "robert.taylor@example.com",
    address: "302 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["None"],
      previous_conditions: ["Tooth Sensitivity", "Hypertension"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A8353",
      date: "2025-11-17",
      time: "8:30 PM",
      dentist: "Dr. Brown",
      procedure: "Teeth Cleaning",
      status: "Cancelled",
      treatment_status: "Completed",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-05-30",
      procedure: "Cavity Filling",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV6026",
      total_amount: 186.72,
      paid_amount: 50.38,
      balance_due: 136.34,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "BC771794445",
      insurance_annual_limit: 2000,
      insurance_used: 1210,
      insurance_remaining: 790,
    },
  },
  {
    patient_id: "P046",
    name: "William Taylor",
    gender: "Female",
    age: 70,
    date_of_birth: "1955-03-26",
    phone: "+1 797-831-8175",
    email: "william.taylor@example.com",
    address: "385 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: [],
      previous_conditions: ["Gum Disease", "Gingivitis"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A2883",
      date: "2025-04-06",
      time: "9:30 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Root Canal",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Wisdom tooth extraction soon",
    last_visit: {
      date: "2024-08-09",
      procedure: "Root Canal",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV7884",
      total_amount: 145.7,
      paid_amount: 95.11,
      balance_due: 50.59,
      payment_status: "Partial",
      payment_method: "Credit Card",
    },
    insurance: {
      insurance_provider: "Cigna",
      insurance_policy_number: "CG928189632",
      insurance_annual_limit: 2000,
      insurance_used: 1045,
      insurance_remaining: 955,
    },
  },
  {
    patient_id: "P047",
    name: "Linda Moore",
    gender: "Female",
    age: 75,
    date_of_birth: "1950-05-16",
    phone: "+1 153-631-8628",
    email: "linda.moore@example.com",
    address: "348 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Tooth Sensitivity", "Gingivitis"],
      current_medications: ["Paracetamol"],
    },
    appointments: {
      appointment_id: "A9107",
      date: "2025-02-24",
      time: "12:00 AM",
      dentist: "Dr. Brown",
      procedure: "Braces Adjustment",
      status: "Scheduled",
      treatment_status: "Ongoing",
    },
    note: "Tooth sensitivity, monitor diet",
    last_visit: {
      date: "2024-04-01",
      procedure: "Teeth Cleaning",
      dentist: "Dr. Brown",
    },
    billing: {
      invoice_id: "INV7411",
      total_amount: 247.15,
      paid_amount: 220.35,
      balance_due: 26.8,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "Delta Dental",
      insurance_policy_number: "MC885903904",
      insurance_annual_limit: 2000,
      insurance_used: 185,
      insurance_remaining: 1815,
    },
  },
  {
    patient_id: "P048",
    name: "William Walker",
    gender: "Male",
    age: 30,
    date_of_birth: "1995-07-02",
    phone: "+1 839-549-5274",
    email: "william.walker@example.com",
    address: "266 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Pollen"],
      previous_conditions: ["Diabetes"],
      current_medications: ["Ibuprofen"],
    },
    appointments: {
      appointment_id: "A3148",
      date: "2025-06-02",
      time: "8:30 PM",
      dentist: "Dr. Lee",
      procedure: "Teeth Cleaning",
      status: "Cancelled",
      treatment_status: "Scheduled",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-10-06",
      procedure: "Root Canal",
      dentist: "Dr. Lee",
    },
    billing: {
      invoice_id: "INV8542",
      total_amount: 171.11,
      paid_amount: 2.11,
      balance_due: 169.0,
      payment_status: "Partial",
      payment_method: "Debit Card",
    },
    insurance: {
      insurance_provider: "HealthFirst",
      insurance_policy_number: "DD626086862",
      insurance_annual_limit: 2000,
      insurance_used: 360,
      insurance_remaining: 1640,
    },
  },
  {
    patient_id: "P049",
    name: "Robert Moore",
    gender: "Male",
    age: 23,
    date_of_birth: "2002-07-07",
    phone: "+1 647-688-2842",
    email: "robert.moore@example.com",
    address: "717 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Penicillin"],
      previous_conditions: ["Gingivitis"],
      current_medications: ["Amoxicillin"],
    },
    appointments: {
      appointment_id: "A8807",
      date: "2025-06-02",
      time: "10:00 PM",
      dentist: "Dr. Emily Carter",
      procedure: "Cavity Filling",
      status: "Scheduled",
      treatment_status: "Ongoing",
    },
    note: "Routine cleaning completed",
    last_visit: {
      date: "2024-04-27",
      procedure: "Extraction",
      dentist: "Dr. Emily Carter",
    },
    billing: {
      invoice_id: "INV6237",
      total_amount: 274.47,
      paid_amount: 240.46,
      balance_due: 34.01,
      payment_status: "Partial",
      payment_method: "Insurance",
    },
    insurance: {
      insurance_provider: "Blue Cross",
      insurance_policy_number: "HF329364008",
      insurance_annual_limit: 2000,
      insurance_used: 1204,
      insurance_remaining: 796,
    },
  },
  {
    patient_id: "P050",
    name: "Richard King",
    gender: "Male",
    age: 62,
    date_of_birth: "1963-10-16",
    phone: "+1 399-339-6406",
    email: "richard.king@example.com",
    address: "472 Main St, Springfield, IL, USA",
    medical_history: {
      allergies: ["Latex"],
      previous_conditions: ["Hypertension", "Gum Disease"],
      current_medications: [],
    },
    appointments: {
      appointment_id: "A9138",
      date: "2025-10-08",
      time: "8:00 AM",
      dentist: "Dr. Lee",
      procedure: "Extraction",
      status: "Cancelled",
      treatment_status: "Completed",
    },
    note: "Braces adjustment successful",
    last_visit: {
      date: "2024-09-08",
      procedure: "Cavity Filling",
      dentist: "Dr. Lee",
    },
    billing: {
      invoice_id: "INV8145",
      total_amount: 216.73,
      paid_amount: 153.0,
      balance_due: 63.73,
      payment_status: "Partial",
      payment_method: "Cash",
    },
    insurance: {
      insurance_provider: "MediCare",
      insurance_policy_number: "MC650874174",
      insurance_annual_limit: 2000,
      insurance_used: 535,
      insurance_remaining: 1465,
    },
  },
];
