export const patients = [
  {
    patient_id: "P001",
    name: "Elizabeth Taylor",
    age: 39,
    gender: "Female",
    phone: "+17100904979",
    email: "elizabethtaylor@example.com",
    medical_history: ["Tooth Sensitivity"],

    treatment: "Crowns & Bridges",
    treatment_status: "Recovered",
    appointment_status:"Upcoming",

    description: "Treatment for no major issues.",
    last_dental_visit: "2023-04-27",
    diagnosis: "No Major Issues",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-11-17",
    dentist_name: "Dr. Thompson",
    current_issue: "Mild discomfort",

    insurance: {
      provider: "HealthFirst",
      policy_number: "HF9658506915",
    },
    heart_rate: 63,
    respiratory_rate: 12,
    temperature: 99.2,
  },
  {
    patient_id: "P002",
    name: "David Young",
    age: 34,
    gender: "Male",
    phone: "+11859153762",
    email: "davidyoung@example.com",
    medical_history: [
      "Wisdom Tooth Issues",
      "Tooth Sensitivity",
      "Gum Disease",
    ],

    treatment: "Cavity Filling",
    date: "2021-06-12",
    dentist: "Dr. Carter",
    description: "Treatment for tooth decay.",
    treatment_status: "Recovered",
    appointment_status:"Completed",

    insurance: {
      provider: "Blue Cross",
      policy_number: "HF2110851445",
    },
    last_dental_visit: "2023-03-26",
    diagnosis: "Tooth Decay",
    treatment_plan: "Extraction",
    next_appointment: "2025-04-07",
    dentist_name: "Dr. Carter",
    current_issue: "Mild discomfort",
    heart_rate: 82,
    respiratory_rate: 24,
    temperature: 98.6,
  },
  {
    patient_id: "P003",
    name: "Emily Hall",
    age: 47,
    gender: "Male",
    phone: "+17212227953",
    email: "emilyhall@example.com",
    medical_history: ["No Allergies", "Diabetes"],

    treatment: "Tooth Extraction",
    date: "2022-11-05",
    dentist: "Dr. Brown",
    description: "Treatment for tooth decay.",
    treatment_status: "Inactive",
    appointment_status:"Cancelled",

    insurance: {
      provider: "Blue Cross",
      policy_number: "HF6428403339",
    },
    last_dental_visit: "2023-05-16",
    diagnosis: "Tooth Decay",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-12-28",
    dentist_name: "Dr. Brown",
    current_issue: "Severe tooth pain",
    heart_rate: 86,
    respiratory_rate: 16,
    temperature: 98.7,
  },
  {
    patient_id: "P004",
    name: "David Young",
    age: 24,
    gender: "Male",
    phone: "+14308940473",
    email: "davidyoung@example.com",
    medical_history: ["Mild Gingivitis", "Hypertension"],

    treatment: "Crowns & Bridges",
    date: "2021-02-14",
    dentist: "Dr. Thompson",
    description: "Treatment for no major issues.",
    treatment_status: "Cured",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Cigna",
      policy_number: "MC1203090360",
    },
    last_dental_visit: "2023-01-27",
    diagnosis: "No Major Issues",
    treatment_plan: "Root Canal",
    next_appointment: "2025-07-03",
    dentist_name: "Dr. Thompson",
    current_issue: "No major complaints",
    heart_rate: 60,
    respiratory_rate: 20,
    temperature: 99.4,
  },
  {
    patient_id: "P005",
    name: "Joseph Davis",
    age: 23,
    gender: "Female",
    phone: "+17046916780",
    email: "josephdavis@example.com",
    medical_history: ["No Allergies", "Allergic to Penicillin", "Gum Disease"],

    treatment: "Teeth Whitening",
    date: "2022-04-01",
    dentist: "Dr. Carter",
    description: "Treatment for cavity.",
    treatment_status: "Ongoing",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Delta Dental",
      policy_number: "MC5070474468",
    },
    last_dental_visit: "2023-03-28",
    diagnosis: "Cavity",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-06-01",
    dentist_name: "Dr. Carter",
    current_issue: "Severe tooth pain",
    heart_rate: 97,
    respiratory_rate: 23,
    temperature: 99.7,
  },
  {
    patient_id: "P006",
    name: "David Allen",
    age: 49,
    gender: "Male",
    phone: "+19896484459",
    email: "davidallen@example.com",
    medical_history: ["Asthma"],

    treatment: "Wisdom Tooth Removal",
    date: "2021-06-14",
    dentist: "Dr. Martinez",
    description: "Treatment for tooth decay.",
    treatment_status: "Cured",
    appointment_status:"Completed",

    insurance: {
      provider: "Delta Dental",
      policy_number: "DD5089259276",
    },
    last_dental_visit: "2023-02-18",
    diagnosis: "Tooth Decay",
    treatment_plan: "Filling",
    next_appointment: "2025-12-03",
    dentist_name: "Dr. Martinez",
    current_issue: "Mild discomfort",
    heart_rate: 98,
    respiratory_rate: 14,
    temperature: 99.6,
  },
  {
    patient_id: "P007",
    name: "Emily Young",
    age: 57,
    gender: "Male",
    phone: "+11591019571",
    email: "emilyyoung@example.com",
    medical_history: [
      "Mild Gingivitis",
      "Allergic to Penicillin",
      "Gum Disease",
    ],

    treatment: "Tooth Extraction",
    date: "2022-09-08",
    dentist: "Dr. Smith",
    description: "Treatment for no major issues.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Blue Cross",
      policy_number: "DD4029954073",
    },
    last_dental_visit: "2023-06-27",
    diagnosis: "No Major Issues",
    treatment_plan: "Filling",
    next_appointment: "2025-05-14",
    dentist_name: "Dr. Smith",
    current_issue: "Mild discomfort",
    heart_rate: 82,
    respiratory_rate: 17,
    temperature: 97.7,
  },
  {
    patient_id: "P008",
    name: "James Brown",
    age: 40,
    gender: "Male",
    phone: "+15143481605",
    email: "jamesbrown@example.com",
    medical_history: ["Mild Gingivitis", "Diabetes", "Gum Disease"],

    treatment: "Routine Cleaning",
    date: "2023-07-14",
    dentist: "Dr. Clark",
    description: "Treatment for tooth decay.",
    treatment_status: "Inactive",
    appointment_status:"Cancelled",

    insurance: {
      provider: "MediCare",
      policy_number: "BC1301635826",
    },
    last_dental_visit: "2023-02-08",
    diagnosis: "Tooth Decay",
    treatment_plan: "Filling",
    next_appointment: "2025-05-08",
    dentist_name: "Dr. Clark",
    current_issue: "Mild discomfort",
    heart_rate: 68,
    respiratory_rate: 21,
    temperature: 97.2,
  },
  {
    patient_id: "P009",
    name: "Barbara Taylor",
    age: 47,
    gender: "Male",
    phone: "+12399482062",
    email: "barbarataylor@example.com",
    medical_history: ["Tooth Sensitivity", "No Allergies"],

    treatment: "Braces Adjustment",
    date: "2022-12-24",
    dentist: "Dr. Clark",
    description: "Treatment for gum infection.",
    treatment_status: "Recovered",
    appointment_status:"Completed",

    insurance: {
      provider: "Delta Dental",
      policy_number: "MC1850711800",
    },
    last_dental_visit: "2023-01-13",
    diagnosis: "Gum Infection",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-06-10",
    dentist_name: "Dr. Clark",
    current_issue: "No major complaints",
    heart_rate: 60,
    respiratory_rate: 18,
    temperature: 99.6,
  },
  {
    patient_id: "P010",
    name: "Emily Walker",
    age: 65,
    gender: "Male",
    phone: "+18020180187",
    email: "emilywalker@example.com",
    medical_history: ["Hypertension"],

    treatment: "Gum Disease Treatment",
    date: "2022-06-17",
    dentist: "Dr. Smith",
    description: "Treatment for cavity.",
    treatment_status: "Recovered",
    appointment_status:"Completed",

    insurance: {
      provider: "HealthFirst",
      policy_number: "BC3265494915",
    },
    last_dental_visit: "2023-01-21",
    diagnosis: "Cavity",
    treatment_plan: "Filling",
    next_appointment: "2025-06-04",
    dentist_name: "Dr. Smith",
    current_issue: "Mild discomfort",
    heart_rate: 80,
    respiratory_rate: 22,
    temperature: 97.1,
  },
  {
    patient_id: "P011",
    name: "Richard Taylor",
    age: 70,
    gender: "Female",
    phone: "+15200309170",
    email: "richardtaylor@example.com",
    medical_history: ["Allergic to Penicillin", "Tooth Sensitivity"],

    treatment: "Tooth Extraction",
    date: "2021-07-07",
    dentist: "Dr. Smith",
    description: "Treatment for no major issues.",
    treatment_status: "Recovered",
    appointment_status:"Upcoming",

    insurance: {
      provider: "MediCare",
      policy_number: "DD3972110392",
    },
    last_dental_visit: "2024-03-21",
    diagnosis: "No Major Issues",
    treatment_plan: "Scaling",
    next_appointment: "2025-09-16",
    dentist_name: "Dr. Smith",
    current_issue: "Severe tooth pain",
    heart_rate: 86,
    respiratory_rate: 15,
    temperature: 98.4,
  },
  {
    patient_id: "P012",
    name: "William Wright",
    age: 49,
    gender: "Male",
    phone: "+14773940033",
    email: "williamwright@example.com",
    medical_history: ["Wisdom Tooth Issues"],

    treatment: "Braces Adjustment",
    date: "2021-08-27",
    dentist: "Dr. Brown",
    description: "Treatment for gum infection.",
    treatment_status: "Cured",
    appointment_status:"Upcoming",

    insurance: {
      provider: "HealthFirst",
      policy_number: "CG1096214604",
    },
    last_dental_visit: "2023-02-09",
    diagnosis: "Gum Infection",
    treatment_plan: "Filling",
    next_appointment: "2025-02-08",
    dentist_name: "Dr. Brown",
    current_issue: "No major complaints",
    heart_rate: 85,
    respiratory_rate: 25,
    temperature: 99.5,
  },
  {
    patient_id: "P013",
    name: "Thomas King",
    age: 38,
    gender: "Male",
    phone: "+17109402780",
    email: "thomasking@example.com",
    medical_history: [
      "Allergic to Penicillin",
      "High Blood Pressure",
      "Hypertension",
    ],

    treatment: "Braces Adjustment",
    date: "2023-09-11",
    dentist: "Dr. Thompson",
    description: "Treatment for cavity.",
    treatment_status: "Cured",
    appointment_status:"Upcoming",

    insurance: {
      provider: "HealthFirst",
      policy_number: "CG4936113907",
    },
    last_dental_visit: "2024-05-09",
    diagnosis: "Cavity",
    treatment_plan: "Scaling",
    next_appointment: "2025-05-14",
    dentist_name: "Dr. Thompson",
    current_issue: "No major complaints",
    heart_rate: 60,
    respiratory_rate: 14,
    temperature: 99.9,
  },
  {
    patient_id: "P014",
    name: "Michael King",
    age: 68,
    gender: "Male",
    phone: "+15632157766",
    email: "michaelking@example.com",
    medical_history: ["Tooth Sensitivity", "Gum Disease"],

    treatment: "Root Canal",
    date: "2021-07-01",
    dentist: "Dr. Brown",
    description: "Treatment for no major issues.",
    treatment_status: "Cured",
    appointment_status:"Completed",

    insurance: {
      provider: "Cigna",
      policy_number: "MC2556901556",
    },
    last_dental_visit: "2024-02-01",
    diagnosis: "No Major Issues",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-03-23",
    dentist_name: "Dr. Brown",
    current_issue: "Severe tooth pain",
    heart_rate: 61,
    respiratory_rate: 13,
    temperature: 98.6,
  },
  {
    patient_id: "P015",
    name: "Jennifer Hall",
    age: 49,
    gender: "Male",
    phone: "+14402468962",
    email: "jenniferhall@example.com",
    medical_history: ["Allergic to Penicillin", "Gum Disease", "Hypertension"],

    treatment: "Cavity Filling",
    date: "2021-11-20",
    dentist: "Dr. Clark",
    description: "Treatment for no major issues.",
    treatment_status: "Ongoing",
    appointment_status:"Completed",

    insurance: {
      provider: "Cigna",
      policy_number: "MC5736391254",
    },
    last_dental_visit: "2023-09-19",
    diagnosis: "No Major Issues",
    treatment_plan: "Extraction",
    next_appointment: "2025-05-07",
    dentist_name: "Dr. Clark",
    current_issue: "Mild discomfort",
    heart_rate: 65,
    respiratory_rate: 23,
    temperature: 99.4,
  },
  {
    patient_id: "P016",
    name: "Susan Lewis",
    age: 35,
    gender: "Female",
    phone: "+15784135514",
    email: "susanlewis@example.com",
    medical_history: ["High Blood Pressure", "Gum Disease"],

    treatment: "Crowns & Bridges",
    date: "2023-01-20",
    dentist: "Dr. Lee",
    description: "Treatment for no major issues.",
    treatment_status: "Recovered",
    appointment_status:"Completed",

    insurance: {
      provider: "Cigna",
      policy_number: "HF9170331510",
    },
    last_dental_visit: "2023-12-02",
    diagnosis: "No Major Issues",
    treatment_plan: "Extraction",
    next_appointment: "2025-10-26",
    dentist_name: "Dr. Lee",
    current_issue: "Severe tooth pain",
    heart_rate: 80,
    respiratory_rate: 21,
    temperature: 99.6,
  },
  {
    patient_id: "P017",
    name: "Elizabeth Brown",
    age: 71,
    gender: "Male",
    phone: "+14463253729",
    email: "elizabethbrown@example.com",
    medical_history: ["Asthma", "Gum Disease", "No Allergies"],

    treatment: "Wisdom Tooth Removal",
    date: "2023-06-28",
    dentist: "Dr. Clark",
    description: "Treatment for gum infection.",
    treatment_status: "Ongoing",
    appointment_status:"Completed",

    insurance: {
      provider: "Cigna",
      policy_number: "HF2609169984",
    },
    last_dental_visit: "2024-11-02",
    diagnosis: "Gum Infection",
    treatment_plan: "Scaling",
    next_appointment: "2025-07-20",
    dentist_name: "Dr. Clark",
    current_issue: "Severe tooth pain",
    heart_rate: 75,
    respiratory_rate: 17,
    temperature: 97.1,
  },
  {
    patient_id: "P018",
    name: "Robert Davis",
    age: 68,
    gender: "Female",
    phone: "+15835194344",
    email: "robertdavis@example.com",
    medical_history: ["Gum Disease"],

    treatment: "Scaling",
    date: "2023-07-10",
    dentist: "Dr. Thompson",
    description: "Treatment for no major issues.",
    treatment_status: "Under Observation",
    appointment_status:"Completed",

    insurance: {
      provider: "Blue Cross",
      policy_number: "HF6295856184",
    },
    last_dental_visit: "2024-12-11",
    diagnosis: "No Major Issues",
    treatment_plan: "Root Canal",
    next_appointment: "2025-08-14",
    dentist_name: "Dr. Thompson",
    current_issue: "Mild discomfort",
    heart_rate: 99,
    respiratory_rate: 17,
    temperature: 99.3,
  },
  {
    patient_id: "P019",
    name: "Barbara Wilson",
    age: 28,
    gender: "Female",
    phone: "+15259047601",
    email: "barbarawilson@example.com",
    medical_history: ["High Blood Pressure", "Hypertension"],

    treatment: "Braces Adjustment",
    date: "2021-09-25",
    dentist: "Dr. Brown",
    description: "Treatment for gum infection.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Delta Dental",
      policy_number: "CG6290394907",
    },
    last_dental_visit: "2023-12-06",
    diagnosis: "Gum Infection",
    treatment_plan: "Extraction",
    next_appointment: "2025-04-26",
    dentist_name: "Dr. Brown",
    current_issue: "Severe tooth pain",
    heart_rate: 91,
    respiratory_rate: 16,
    temperature: 98.6,
  },
  {
    patient_id: "P020",
    name: "Susan Young",
    age: 27,
    gender: "Female",
    phone: "+19136661093",
    email: "susanyoung@example.com",
    medical_history: ["Gum Disease"],

    treatment: "Gum Disease Treatment",
    date: "2022-05-06",
    dentist: "Dr. Lee",
    description: "Treatment for no major issues.",
    treatment_status: "Cured",
    appointment_status:"Cancelled",

    insurance: {
      provider: "Delta Dental",
      policy_number: "HF6559768285",
    },
    last_dental_visit: "2023-01-26",
    diagnosis: "No Major Issues",
    treatment_plan: "Scaling",
    next_appointment: "2025-01-08",
    dentist_name: "Dr. Lee",
    current_issue: "Severe tooth pain",
    heart_rate: 87,
    respiratory_rate: 23,
    temperature: 99.6,
  },
  {
    patient_id: "P021",
    name: "Elizabeth Taylor",
    age: 64,
    gender: "Male",
    phone: "+12408265546",
    email: "elizabethtaylor@example.com",
    medical_history: ["Asthma", "Diabetes", "Wisdom Tooth Issues"],

    treatment: "Crowns & Bridges",
    date: "2021-10-19",
    dentist: "Dr. Martinez",
    description: "Treatment for gum infection.",
    treatment_status: "Recovered",
    appointment_status:"Cancelled",

    insurance: {
      provider: "Blue Cross",
      policy_number: "BC7819511179",
    },
    last_dental_visit: "2023-08-24",
    diagnosis: "Gum Infection",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-07-15",
    dentist_name: "Dr. Martinez",
    current_issue: "No major complaints",
    heart_rate: 97,
    respiratory_rate: 12,
    temperature: 99.4,
  },
  {
    patient_id: "P022",
    name: "Charles Brown",
    age: 46,
    gender: "Male",
    phone: "+15263817469",
    email: "charlesbrown@example.com",
    medical_history: ["No Allergies"],

    treatment: "Teeth Whitening",
    date: "2022-04-25",
    dentist: "Dr. Martinez",
    description: "Treatment for cavity.",
    treatment_status: "Under Observation",
    appointment_status:"Completed",

    insurance: {
      provider: "Cigna",
      policy_number: "MC3130472728",
    },
    last_dental_visit: "2024-06-11",
    diagnosis: "Cavity",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-01-03",
    dentist_name: "Dr. Martinez",
    current_issue: "Severe tooth pain",
    heart_rate: 68,
    respiratory_rate: 17,
    temperature: 98.8,
  },
  {
    patient_id: "P023",
    name: "Michael Allen",
    age: 57,
    gender: "Male",
    phone: "+18214181017",
    email: "michaelallen@example.com",
    medical_history: ["Hypertension", "Gum Disease", "Diabetes"],

    treatment: "Tooth Extraction",
    date: "2023-04-28",
    dentist: "Dr. Smith",
    description: "Treatment for cavity.",
    treatment_status: "Recovered",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Blue Cross",
      policy_number: "MC9202530739",
    },
    last_dental_visit: "2024-03-09",
    diagnosis: "Cavity",
    treatment_plan: "Filling",
    next_appointment: "2025-06-27",
    dentist_name: "Dr. Smith",
    current_issue: "Severe tooth pain",
    heart_rate: 80,
    respiratory_rate: 12,
    temperature: 99.1,
  },
  {
    patient_id: "P024",
    name: "Jane Smith",
    age: 48,
    gender: "Female",
    phone: "+17358972206",
    email: "janesmith@example.com",
    medical_history: ["Tooth Sensitivity"],

    treatment: "Root Canal",
    date: "2023-03-14",
    dentist: "Dr. Smith",
    description: "Treatment for plaque buildup.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Cigna",
      policy_number: "HF8465966156",
    },
    last_dental_visit: "2024-07-01",
    diagnosis: "Plaque Buildup",
    treatment_plan: "Scaling",
    next_appointment: "2025-05-11",
    dentist_name: "Dr. Smith",
    current_issue: "No major complaints",
    heart_rate: 65,
    respiratory_rate: 15,
    temperature: 97.1,
  },
  {
    patient_id: "P025",
    name: "William Wright",
    age: 35,
    gender: "Female",
    phone: "+11909645831",
    email: "williamwright@example.com",
    medical_history: ["Diabetes"],

    treatment: "Wisdom Tooth Removal",
    date: "2023-09-19",
    dentist: "Dr. Thompson",
    description: "Treatment for plaque buildup.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Delta Dental",
      policy_number: "DD7652810932",
    },
    last_dental_visit: "2023-05-21",
    diagnosis: "Plaque Buildup",
    treatment_plan: "Filling",
    next_appointment: "2025-07-13",
    dentist_name: "Dr. Thompson",
    current_issue: "Mild discomfort",
    heart_rate: 97,
    respiratory_rate: 21,
    temperature: 97.0,
  },
  {
    patient_id: "P026",
    name: "Sarah Harris",
    age: 60,
    gender: "Female",
    phone: "+19447948050",
    email: "sarahharris@example.com",
    medical_history: ["High Blood Pressure", "Diabetes"],

    treatment: "Wisdom Tooth Removal",
    date: "2023-03-22",
    dentist: "Dr. Thompson",
    description: "Treatment for cavity.",
    treatment_status: "Cured",
    appointment_status:"Completed",

    insurance: {
      provider: "Blue Cross",
      policy_number: "HF4985546987",
    },
    last_dental_visit: "2023-01-02",
    diagnosis: "Cavity",
    treatment_plan: "Scaling",
    next_appointment: "2025-06-05",
    dentist_name: "Dr. Thompson",
    current_issue: "Severe tooth pain",
    heart_rate: 80,
    respiratory_rate: 12,
    temperature: 98.5,
  },
  {
    patient_id: "P027",
    name: "William Scott",
    age: 73,
    gender: "Female",
    phone: "+13711563438",
    email: "williamscott@example.com",
    medical_history: ["Diabetes"],

    treatment: "Teeth Whitening",
    date: "2022-07-20",
    dentist: "Dr. Martinez",
    description: "Treatment for no major issues.",
    treatment_status: "Recovered",
    appointment_status:"Completed",

    insurance: {
      provider: "Delta Dental",
      policy_number: "MC2469449600",
    },
    last_dental_visit: "2024-10-02",
    diagnosis: "No Major Issues",
    treatment_plan: "Filling",
    next_appointment: "2025-01-05",
    dentist_name: "Dr. Martinez",
    current_issue: "No major complaints",
    heart_rate: 76,
    respiratory_rate: 19,
    temperature: 98.2,
  },
  {
    patient_id: "P028",
    name: "Barbara King",
    age: 31,
    gender: "Male",
    phone: "+16179120086",
    email: "barbaraking@example.com",
    medical_history: ["Hypertension", "Asthma", "Gum Disease"],

    treatment: "Cavity Filling",
    date: "2022-02-24",
    dentist: "Dr. Smith",
    description: "Treatment for plaque buildup.",
    treatment_status: "Cured",
    appointment_status:"Completed",

    insurance: {
      provider: "Cigna",
      policy_number: "CG6805309790",
    },
    last_dental_visit: "2024-05-10",
    diagnosis: "Plaque Buildup",
    treatment_plan: "Root Canal",
    next_appointment: "2025-07-10",
    dentist_name: "Dr. Smith",
    current_issue: "No major complaints",
    heart_rate: 75,
    respiratory_rate: 12,
    temperature: 99.3,
  },
  {
    patient_id: "P029",
    name: "Patricia Allen",
    age: 24,
    gender: "Male",
    phone: "+18531855127",
    email: "patriciaallen@example.com",
    medical_history: ["Allergic to Penicillin"],

    treatment: "Wisdom Tooth Removal",
    date: "2023-06-06",
    dentist: "Dr. Brown",
    description: "Treatment for gum infection.",
    treatment_status: "Ongoing",
    appointment_status:"Cancelled",

    insurance: {
      provider: "Cigna",
      policy_number: "CG4054154969",
    },
    last_dental_visit: "2023-01-08",
    diagnosis: "Gum Infection",
    treatment_plan: "Extraction",
    next_appointment: "2025-12-26",
    dentist_name: "Dr. Brown",
    current_issue: "Severe tooth pain",
    heart_rate: 81,
    respiratory_rate: 15,
    temperature: 99.2,
  },
  {
    patient_id: "P030",
    name: "William Harris",
    age: 43,
    gender: "Male",
    phone: "+15289396894",
    email: "williamharris@example.com",
    medical_history: ["Gum Disease", "Mild Gingivitis"],

    treatment: "Teeth Whitening",
    date: "2022-07-04",
    dentist: "Dr. Carter",
    description: "Treatment for no major issues.",
    treatment_status: "Ongoing",
    appointment_status:"Cancelled",

    insurance: {
      provider: "HealthFirst",
      policy_number: "BC2390790159",
    },
    last_dental_visit: "2023-08-24",
    diagnosis: "No Major Issues",
    treatment_plan: "Root Canal",
    next_appointment: "2025-06-26",
    dentist_name: "Dr. Carter",
    current_issue: "No major complaints",
    heart_rate: 77,
    respiratory_rate: 14,
    temperature: 99.8,
  },
  {
    patient_id: "P031",
    name: "Linda Smith",
    age: 65,
    gender: "Female",
    phone: "+11399665178",
    email: "lindasmith@example.com",
    medical_history: ["Gum Disease", "Allergic to Penicillin"],

    treatment: "Root Canal",
    date: "2022-01-17",
    dentist: "Dr. Lee",
    description: "Treatment for gum infection.",
    treatment_status: "Cured",
    appointment_status:"Completed",

    insurance: {
      provider: "Delta Dental",
      policy_number: "DD3619443606",
    },
    last_dental_visit: "2023-03-20",
    diagnosis: "Gum Infection",
    treatment_plan: "Scaling",
    next_appointment: "2025-10-28",
    dentist_name: "Dr. Lee",
    current_issue: "Severe tooth pain",
    heart_rate: 76,
    respiratory_rate: 14,
    temperature: 97.9,
  },
  {
    patient_id: "P032",
    name: "Barbara Doe",
    age: 20,
    gender: "Male",
    phone: "+19709736046",
    email: "barbaradoe@example.com",
    medical_history: ["Asthma", "Gum Disease", "No Allergies"],

    treatment: "Root Canal",
    date: "2021-10-26",
    dentist: "Dr. Clark",
    description: "Treatment for gum infection.",
    treatment_status: "Cured",
    appointment_status:"Upcoming",

    insurance: {
      provider: "MediCare",
      policy_number: "MC2355246702",
    },
    last_dental_visit: "2023-07-19",
    diagnosis: "Gum Infection",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-11-09",
    dentist_name: "Dr. Clark",
    current_issue: "Severe tooth pain",
    heart_rate: 96,
    respiratory_rate: 23,
    temperature: 97.5,
  },
  {
    patient_id: "P033",
    name: "Patricia Scott",
    age: 19,
    gender: "Female",
    phone: "+17884251530",
    email: "patriciascott@example.com",
    medical_history: ["Mild Gingivitis"],

    treatment: "Cavity Filling",
    date: "2021-07-11",
    dentist: "Dr. Brown",
    description: "Treatment for cavity.",
    treatment_status: "Recovered",
    appointment_status:"Upcoming",

    insurance: {
      provider: "HealthFirst",
      policy_number: "CG7775246500",
    },
    last_dental_visit: "2023-01-20",
    diagnosis: "Cavity",
    treatment_plan: "Scaling",
    next_appointment: "2025-02-09",
    dentist_name: "Dr. Brown",
    current_issue: "Severe tooth pain",
    heart_rate: 96,
    respiratory_rate: 12,
    temperature: 97.9,
  },
  {
    patient_id: "P034",
    name: "Richard Lewis",
    age: 42,
    gender: "Male",
    phone: "+15858908731",
    email: "richardlewis@example.com",
    medical_history: ["No Allergies"],

    treatment: "Crowns & Bridges",
    date: "2021-09-26",
    dentist: "Dr. Clark",
    description: "Treatment for gum infection.",
    treatment_status: "Under Observation",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Cigna",
      policy_number: "CG5977003328",
    },
    last_dental_visit: "2023-03-17",
    diagnosis: "Gum Infection",
    treatment_plan: "Filling",
    next_appointment: "2025-03-17",
    dentist_name: "Dr. Clark",
    current_issue: "Severe tooth pain",
    heart_rate: 70,
    respiratory_rate: 14,
    temperature: 99.4,
  },
  {
    patient_id: "P035",
    name: "Sarah Davis",
    age: 60,
    gender: "Male",
    phone: "+11527194021",
    email: "sarahdavis@example.com",
    medical_history: ["Diabetes", "High Blood Pressure", "Wisdom Tooth Issues"],

    treatment: "Routine Cleaning",
    date: "2022-12-04",
    dentist: "Dr. Carter",
    description: "Treatment for no major issues.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Cigna",
      policy_number: "DD4235044439",
    },
    last_dental_visit: "2024-11-04",
    diagnosis: "No Major Issues",
    treatment_plan: "Root Canal",
    next_appointment: "2025-01-09",
    dentist_name: "Dr. Carter",
    current_issue: "No major complaints",
    heart_rate: 93,
    respiratory_rate: 17,
    temperature: 98.6,
  },
  {
    patient_id: "P036",
    name: "Sarah Harris",
    age: 28,
    gender: "Male",
    phone: "+19635216822",
    email: "sarahharris@example.com",
    medical_history: [
      "Diabetes",
      "Tooth Sensitivity",
      "Allergic to Penicillin",
    ],

    treatment: "Braces Adjustment",
    date: "2021-11-08",
    dentist: "Dr. Clark",
    description: "Treatment for gum infection.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "HealthFirst",
      policy_number: "MC1781553143",
    },
    last_dental_visit: "2023-06-23",
    diagnosis: "Gum Infection",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-12-14",
    dentist_name: "Dr. Clark",
    current_issue: "No major complaints",
    heart_rate: 97,
    respiratory_rate: 23,
    temperature: 98.8,
  },
  {
    patient_id: "P037",
    name: "Linda Moore",
    age: 22,
    gender: "Male",
    phone: "+18624422769",
    email: "lindamoore@example.com",
    medical_history: ["Gum Disease", "Wisdom Tooth Issues"],

    treatment: "Tooth Extraction",
    date: "2023-04-21",
    dentist: "Dr. Thompson",
    description: "Treatment for tooth decay.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Cigna",
      policy_number: "DD4024790850",
    },
    last_dental_visit: "2024-09-04",
    diagnosis: "Tooth Decay",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-08-27",
    dentist_name: "Dr. Thompson",
    current_issue: "Mild discomfort",
    heart_rate: 72,
    respiratory_rate: 21,
    temperature: 98.3,
  },
  {
    patient_id: "P038",
    name: "Emily Doe",
    age: 68,
    gender: "Female",
    phone: "+11485667906",
    email: "emilydoe@example.com",
    medical_history: ["Asthma"],

    treatment: "Wisdom Tooth Removal",
    date: "2023-05-01",
    dentist: "Dr. Smith",
    description: "Treatment for gum infection.",
    treatment_status: "Recovered",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Cigna",
      policy_number: "HF4222617801",
    },
    last_dental_visit: "2024-05-27",
    diagnosis: "Gum Infection",
    treatment_plan: "Root Canal",
    next_appointment: "2025-05-17",
    dentist_name: "Dr. Smith",
    current_issue: "Mild discomfort",
    heart_rate: 64,
    respiratory_rate: 20,
    temperature: 97.7,
  },
  {
    patient_id: "P039",
    name: "Sarah Scott",
    age: 70,
    gender: "Female",
    phone: "+14021005253",
    email: "sarahscott@example.com",
    medical_history: ["Hypertension", "Wisdom Tooth Issues", "Diabetes"],

    treatment: "Wisdom Tooth Removal",
    date: "2022-02-22",
    dentist: "Dr. Lee",
    description: "Treatment for no major issues.",
    treatment_status: "Cured",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Blue Cross",
      policy_number: "BC1549619586",
    },
    last_dental_visit: "2024-02-06",
    diagnosis: "No Major Issues",
    treatment_plan: "Scaling",
    next_appointment: "2025-11-14",
    dentist_name: "Dr. Lee",
    current_issue: "No major complaints",
    heart_rate: 68,
    respiratory_rate: 16,
    temperature: 97.7,
  },
  {
    patient_id: "P040",
    name: "Elizabeth Wright",
    age: 63,
    gender: "Female",
    phone: "+17830203879",
    email: "elizabethwright@example.com",
    medical_history: [
      "Wisdom Tooth Issues",
      "No Allergies",
      "High Blood Pressure",
    ],

    treatment: "Routine Cleaning",
    date: "2023-03-22",
    dentist: "Dr. Carter",
    description: "Treatment for no major issues.",
    treatment_status: "Under Observation",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Delta Dental",
      policy_number: "CG9188477950",
    },
    last_dental_visit: "2024-03-12",
    diagnosis: "No Major Issues",
    treatment_plan: "Filling",
    next_appointment: "2025-11-22",
    dentist_name: "Dr. Carter",
    current_issue: "Mild discomfort",
    heart_rate: 81,
    respiratory_rate: 21,
    temperature: 98.3,
  },
  {
    patient_id: "P041",
    name: "John Wright",
    age: 32,
    gender: "Male",
    phone: "+11624676296",
    email: "johnwright@example.com",
    medical_history: ["High Blood Pressure", "Tooth Sensitivity"],

    treatment: "Root Canal",
    date: "2023-03-14",
    dentist: "Dr. Brown",
    description: "Treatment for no major issues.",
    treatment_status: "Ongoing",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Cigna",
      policy_number: "HF8669492792",
    },
    last_dental_visit: "2023-07-14",
    diagnosis: "No Major Issues",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-11-18",
    dentist_name: "Dr. Brown",
    current_issue: "No major complaints",
    heart_rate: 69,
    respiratory_rate: 14,
    temperature: 98.8,
  },
  {
    patient_id: "P042",
    name: "Susan Walker",
    age: 23,
    gender: "Female",
    phone: "+12016966221",
    email: "susanwalker@example.com",
    medical_history: ["Mild Gingivitis"],

    treatment: "Root Canal",
    date: "2023-12-22",
    dentist: "Dr. Brown",
    description: "Treatment for gum infection.",
    treatment_status: "Ongoing",
    appointment_status:"Upcoming",

    insurance: {
      provider: "HealthFirst",
      policy_number: "BC5299692830",
    },
    last_dental_visit: "2023-03-17",
    diagnosis: "Gum Infection",
    treatment_plan: "Scaling",
    next_appointment: "2025-05-01",
    dentist_name: "Dr. Brown",
    current_issue: "Mild discomfort",
    heart_rate: 68,
    respiratory_rate: 15,
    temperature: 99.1,
  },
  {
    patient_id: "P043",
    name: "Charles King",
    age: 29,
    gender: "Male",
    phone: "+17633933151",
    email: "charlesking@example.com",
    medical_history: ["No Allergies"],

    treatment: "Gum Disease Treatment",
    date: "2023-07-23",
    dentist: "Dr. Carter",
    description: "Treatment for plaque buildup.",
    treatment_status: "Under Observation",
    appointment_status:"Upcoming",

    insurance: {
      provider: "MediCare",
      policy_number: "HF5460519774",
    },
    last_dental_visit: "2023-05-03",
    diagnosis: "Plaque Buildup",
    treatment_plan: "Scaling",
    next_appointment: "2025-08-12",
    dentist_name: "Dr. Carter",
    current_issue: "No major complaints",
    heart_rate: 88,
    respiratory_rate: 23,
    temperature: 99.5,
  },
  {
    patient_id: "P044",
    name: "Maria Wright",
    age: 71,
    gender: "Female",
    phone: "+18602419597",
    email: "mariawright@example.com",
    medical_history: ["Asthma"],

    treatment: "Gum Disease Treatment",
    date: "2021-08-19",
    dentist: "Dr. Brown",
    description: "Treatment for tooth decay.",
    treatment_status: "Cured",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Cigna",
      policy_number: "CG2979905268",
    },
    last_dental_visit: "2023-12-19",
    diagnosis: "Tooth Decay",
    treatment_plan: "Extraction",
    next_appointment: "2025-03-02",
    dentist_name: "Dr. Brown",
    current_issue: "Severe tooth pain",
    heart_rate: 99,
    respiratory_rate: 19,
    temperature: 97.7,
  },
  {
    patient_id: "P045",
    name: "David Smith",
    age: 36,
    gender: "Female",
    phone: "+18856627144",
    email: "davidsmith@example.com",
    medical_history: ["Hypertension"],

    treatment: "Wisdom Tooth Removal",
    date: "2023-11-23",
    dentist: "Dr. Carter",
    description: "Treatment for cavity.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Delta Dental",
      policy_number: "MC2071480976",
    },
    last_dental_visit: "2024-03-09",
    diagnosis: "Cavity",
    treatment_plan: "Scaling",
    next_appointment: "2025-09-07",
    dentist_name: "Dr. Carter",
    current_issue: "Severe tooth pain",
    heart_rate: 75,
    respiratory_rate: 13,
    temperature: 97.8,
  },
  {
    patient_id: "P046",
    name: "John Hall",
    age: 71,
    gender: "Male",
    phone: "+14946241973",
    email: "johnhall@example.com",
    medical_history: ["Tooth Sensitivity", "Asthma"],

    treatment: "Wisdom Tooth Removal",
    date: "2021-01-14",
    dentist: "Dr. Smith",
    description: "Treatment for plaque buildup.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Delta Dental",
      policy_number: "DD5518105864",
    },
    last_dental_visit: "2024-03-27",
    diagnosis: "Plaque Buildup",
    treatment_plan: "Filling",
    next_appointment: "2025-10-24",
    dentist_name: "Dr. Smith",
    current_issue: "Mild discomfort",
    heart_rate: 96,
    respiratory_rate: 20,
    temperature: 98.3,
  },
  {
    patient_id: "P047",
    name: "Michael Wilson",
    age: 58,
    gender: "Male",
    phone: "+18007297667",
    email: "michaelwilson@example.com",
    medical_history: ["Hypertension", "High Blood Pressure"],

    treatment: "Root Canal",
    date: "2021-03-02",
    dentist: "Dr. Carter",
    description: "Treatment for gum infection.",
    treatment_status: "Inactive",
    appointment_status:"Upcoming",

    insurance: {
      provider: "MediCare",
      policy_number: "DD5916642061",
    },
    last_dental_visit: "2023-03-01",
    diagnosis: "Gum Infection",
    treatment_plan: "Scaling",
    next_appointment: "2025-11-15",
    dentist_name: "Dr. Carter",
    current_issue: "No major complaints",
    heart_rate: 99,
    respiratory_rate: 22,
    temperature: 98.2,
  },
  {
    patient_id: "P048",
    name: "David Brown",
    age: 23,
    gender: "Female",
    phone: "+13596295319",
    email: "davidbrown@example.com",
    medical_history: [
      "Tooth Sensitivity",
      "Mild Gingivitis",
      "Allergic to Penicillin",
    ],

    treatment: "Root Canal",
    date: "2021-09-26",
    dentist: "Dr. Martinez",
    description: "Treatment for plaque buildup.",
    treatment_status: "Under Observation",
    appointment_status:"Upcoming",

    insurance: {
      provider: "HealthFirst",
      policy_number: "BC1068147312",
    },
    last_dental_visit: "2024-01-13",
    diagnosis: "Plaque Buildup",
    treatment_plan: "Root Canal",
    next_appointment: "2025-11-18",
    dentist_name: "Dr. Martinez",
    current_issue: "Mild discomfort",
    heart_rate: 99,
    respiratory_rate: 23,
    temperature: 98.7,
  },
  {
    patient_id: "P049",
    name: "Jennifer Doe",
    age: 50,
    gender: "Male",
    phone: "+17743882264",
    email: "jenniferdoe@example.com",
    medical_history: ["Diabetes", "Mild Gingivitis"],

    treatment: "Tooth Extraction",
    date: "2023-09-15",
    dentist: "Dr. Smith",
    description: "Treatment for tooth decay.",
    treatment_status: "Ongoing",
    appointment_status:"Upcoming",

    insurance: {
      provider: "HealthFirst",
      policy_number: "BC2027048201",
    },
    last_dental_visit: "2023-03-23",
    diagnosis: "Tooth Decay",
    treatment_plan: "Routine Cleaning",
    next_appointment: "2025-07-15",
    dentist_name: "Dr. Smith",
    current_issue: "No major complaints",
    heart_rate: 72,
    respiratory_rate: 25,
    temperature: 99.9,
  },
  {
    patient_id: "P050",
    name: "James Scott",
    age: 24,
    gender: "Female",
    phone: "+18575925503",
    email: "jamesscott@example.com",
    medical_history: ["Asthma", "Diabetes", "High Blood Pressure"],

    treatment: "Teeth Whitening",
    date: "2022-05-02",
    dentist: "Dr. Smith",
    description: "Treatment for no major issues.",
    treatment_status: "Cured",
    appointment_status:"Upcoming",

    insurance: {
      provider: "Cigna",
      policy_number: "MC1385596661",
    },
    last_dental_visit: "2023-04-01",
    diagnosis: "No Major Issues",
    treatment_plan: "Filling",
    next_appointment: "2025-01-07",
    dentist_name: "Dr. Smith",
    current_issue: "Severe tooth pain",
    heart_rate: 90,
    respiratory_rate: 22,
    temperature: 99.4,
  },
];
